import { BadRequestException, ForbiddenException, Injectable, NotFoundException } from '@nestjs/common';
import { Prisma } from '@prisma/client';
import { AuthService } from '../auth/auth.service';
import { AuthUser } from '../auth/auth.types';
import { PrismaService } from '../prisma/prisma.service';
import { AnalyticsQueryDto, CreateAppealDto, CreateEvaluationTaskDto, CreateReportDto, ReviewAppealDto, SaveReconstructionDto, UpdateIndicatorDto, UpdateReportDto, UpdateRuleDto } from './dto';

@Injectable()
export class AnalyticsService {
  constructor(private prisma: PrismaService, private auth: AuthService) {}

  private isSuper(user: AuthUser) { return user.roles.some((role) => role.code === 'SUPER_ADMIN'); }
  private organizationRelation(user: AuthUser) { return { is: { OR: [{ id: user.organizationId ?? '__none__' }, { parentId: user.organizationId ?? '__none__' }] } }; }
  private scoped(user: AuthUser) {
    if (user.portal === 'ENTERPRISE') {
      if (!user.enterpriseId) throw new ForbiddenException('企业账号尚未关联企业主体');
      return { enterpriseId: user.enterpriseId };
    }
    return this.isSuper(user) ? {} : { organization: this.organizationRelation(user) };
  }
  private enterpriseScoped(user: AuthUser): Prisma.EnterpriseWhereInput {
    if (user.portal === 'ENTERPRISE') return { id: user.enterpriseId ?? '__none__' };
    return this.isSuper(user) ? {} : { organization: this.organizationRelation(user) };
  }
  private page(query: AnalyticsQueryDto) { return { skip: (query.page - 1) * query.pageSize, take: query.pageSize }; }
  private dates(query: AnalyticsQueryDto) {
    const to = query.to ? new Date(`${query.to}T23:59:59.999Z`) : new Date();
    const from = query.from ? new Date(query.from) : new Date(to.getTime() - 29 * 86400000);
    if (from > to) throw new BadRequestException('开始日期不能晚于结束日期');
    return { from, to };
  }
  private dateKey(value: Date) { return value.toISOString().slice(0, 10); }
  private businessNo(prefix: string) { const stamp = new Date().toISOString().replace(/[-:TZ.]/g, '').slice(0, 14); return `${prefix}-${stamp}-${Math.floor(1000 + Math.random() * 9000)}`; }
  private round(value: number, digits = 1) { const scale = 10 ** digits; return Math.round(value * scale) / scale; }
  private rangeDays(from: Date, to: Date, max = 31) { const result: string[] = []; const cursor = new Date(from); cursor.setUTCHours(0, 0, 0, 0); while (cursor <= to && result.length < max) { result.push(this.dateKey(cursor)); cursor.setUTCDate(cursor.getUTCDate() + 1); } return result; }
  private async assertEnterprise(user: AuthUser, enterpriseId: string) {
    const item = await this.prisma.enterprise.findFirst({ where: { ...this.enterpriseScoped(user), id: enterpriseId } });
    if (!item) throw new ForbiddenException('企业不在当前数据范围内');
    return item;
  }

  async options(user: AuthUser) {
    const [enterprises, organizations, vehicles, accidents] = await this.prisma.$transaction([
      this.prisma.enterprise.findMany({ where: { ...this.enterpriseScoped(user), status: 'ACTIVE' }, orderBy: { name: 'asc' }, select: { id: true, name: true, organizationId: true } }),
      this.prisma.organization.findMany({ where: this.isSuper(user) ? {} : { OR: [{ id: user.organizationId ?? '__none__' }, { parentId: user.organizationId ?? '__none__' }] }, orderBy: { name: 'asc' }, select: { id: true, name: true } }),
      this.prisma.vehicle.findMany({ where: { ...this.scoped(user), deletedAt: null }, orderBy: { name: 'asc' }, select: { id: true, name: true, businessNo: true, enterpriseId: true } }),
      this.prisma.accident.findMany({ where: this.scoped(user), orderBy: { occurredAt: 'desc' }, select: { id: true, businessNo: true, title: true, enterpriseId: true, occurredAt: true } }),
    ]);
    return { enterprises, organizations, vehicles, accidents };
  }

  async operationAnalysis(user: AuthUser, query: AnalyticsQueryDto) {
    const { from, to } = this.dates(query);
    const where: Prisma.OperationRecordWhereInput = { ...this.scoped(user), enterpriseId: user.portal === 'ENTERPRISE' ? user.enterpriseId ?? '__none__' : query.enterpriseId, organizationId: query.organizationId, vehicleId: query.vehicleId, startedAt: { gte: from, lte: to } };
    const records = await this.prisma.operationRecord.findMany({ where, orderBy: { startedAt: 'asc' }, include: { enterprise: { select: { id: true, name: true } }, region: { select: { id: true, name: true } }, vehicle: { select: { id: true, name: true } } } });
    const sum = (key: 'mileage' | 'durationMinutes' | 'energyUsed' | 'autonomousMiles' | 'manualTakeovers') => records.reduce((total, row) => total + Number(row[key]), 0);
    const mileage = sum('mileage'), hours = sum('durationMinutes') / 60, autonomous = sum('autonomousMiles');
    const trendMap = new Map<string, { date: string; mileage: number; trips: number; duration: number; energy: number }>();
    this.rangeDays(from, to).forEach((date) => trendMap.set(date, { date, mileage: 0, trips: 0, duration: 0, energy: 0 }));
    for (const row of records) { const key = this.dateKey(row.startedAt); const item = trendMap.get(key) ?? { date: key, mileage: 0, trips: 0, duration: 0, energy: 0 }; item.mileage += row.mileage; item.trips++; item.duration += row.durationMinutes; item.energy += row.energyUsed; trendMap.set(key, item); }
    const enterpriseMap = new Map<string, any>();
    for (const row of records) { const item = enterpriseMap.get(row.enterpriseId) ?? { id: row.enterpriseId, name: row.enterprise.name, mileage: 0, duration: 0, trips: 0, energy: 0, autonomousMiles: 0 }; item.mileage += row.mileage; item.duration += row.durationMinutes; item.trips++; item.energy += row.energyUsed; item.autonomousMiles += row.autonomousMiles; enterpriseMap.set(row.enterpriseId, item); }
    const regionMap = new Map<string, any>(); for (const row of records) { const key = row.region?.id ?? 'unassigned'; const item = regionMap.get(key) ?? { id: key, name: row.region?.name ?? '未关联区域', mileage: 0, trips: 0 }; item.mileage += row.mileage; item.trips++; regionMap.set(key, item); }
    return {
      period: { from, to },
      kpis: { vehicles: new Set(records.map((row) => row.vehicleId)).size, trips: records.length, mileage: this.round(mileage), durationHours: this.round(hours), efficiency: this.round(hours ? mileage / hours : 0), energyUsed: this.round(sum('energyUsed')), autonomousRate: this.round(mileage ? autonomous / mileage * 100 : 0), manualTakeovers: sum('manualTakeovers') },
      trend: [...trendMap.values()].map((item) => ({ ...item, mileage: this.round(item.mileage), durationHours: this.round(item.duration / 60), energy: this.round(item.energy) })),
      enterprises: [...enterpriseMap.values()].map((item) => ({ ...item, mileage: this.round(item.mileage), durationHours: this.round(item.duration / 60), efficiency: this.round(item.duration ? item.mileage / (item.duration / 60) : 0), autonomousRate: this.round(item.mileage ? item.autonomousMiles / item.mileage * 100 : 0) })).sort((a, b) => b.mileage - a.mileage),
      regions: [...regionMap.values()].map((item) => ({ ...item, mileage: this.round(item.mileage) })).sort((a, b) => b.mileage - a.mileage),
    };
  }

  async safetyAnalysis(user: AuthUser, query: AnalyticsQueryDto) {
    const { from, to } = this.dates(query); const base: any = { ...this.scoped(user), enterpriseId: user.portal === 'ENTERPRISE' ? user.enterpriseId ?? '__none__' : query.enterpriseId, organizationId: query.organizationId };
    const [alerts, accidents, violations] = await this.prisma.$transaction([
      this.prisma.safetyAlert.findMany({ where: { ...base, occurredAt: { gte: from, lte: to } }, include: { enterprise: { select: { id: true, name: true } }, vehicle: { select: { id: true, name: true } } } }),
      this.prisma.accident.findMany({ where: { ...base, occurredAt: { gte: from, lte: to } }, include: { enterprise: { select: { id: true, name: true } }, vehicle: { select: { id: true, name: true } } } }),
      this.prisma.violation.findMany({ where: { ...base, occurredAt: { gte: from, lte: to } }, include: { enterprise: { select: { id: true, name: true } }, vehicle: { select: { id: true, name: true } } } }),
    ]);
    const trend = new Map<string, any>(); this.rangeDays(from, to).forEach((date) => trend.set(date, { date, alerts: 0, accidents: 0, violations: 0 }));
    for (const row of alerts) { const item = trend.get(this.dateKey(row.occurredAt)); if (item) item.alerts++; } for (const row of accidents) { const item = trend.get(this.dateKey(row.occurredAt)); if (item) item.accidents++; } for (const row of violations) { const item = trend.get(this.dateKey(row.occurredAt)); if (item) item.violations++; }
    const typeMap = new Map<string, number>(); [...alerts.map((x) => `告警:${x.alertType}`), ...accidents.map((x) => `事故:${x.accidentType}`), ...violations.map((x) => `违规:${x.violationType}`)].forEach((type) => typeMap.set(type, (typeMap.get(type) ?? 0) + 1));
    const enterpriseMap = new Map<string, any>();
    const addRisk = (row: any, kind: string, value: number) => { const item = enterpriseMap.get(row.enterpriseId) ?? { id: row.enterpriseId, name: row.enterprise.name, alerts: 0, accidents: 0, violations: 0, riskScore: 0 }; item[kind]++; item.riskScore += value; enterpriseMap.set(row.enterpriseId, item); };
    alerts.forEach((row) => addRisk(row, 'alerts', ({ LOW: 1, MEDIUM: 2, HIGH: 4, CRITICAL: 8 } as any)[row.level] ?? 2)); accidents.forEach((row) => addRisk(row, 'accidents', ({ LOW: 3, MEDIUM: 6, HIGH: 10, CRITICAL: 16 } as any)[row.level] ?? 6)); violations.forEach((row) => addRisk(row, 'violations', ({ LOW: 2, MEDIUM: 4, HIGH: 7, CRITICAL: 12 } as any)[row.level] ?? 4));
    const riskPoints = [...alerts.map((row) => ({ id: row.id, longitude: row.longitude, latitude: row.latitude, weight: ({ LOW: 2, MEDIUM: 4, HIGH: 7, CRITICAL: 10 } as any)[row.level] ?? 4, kind: 'ALERT', title: row.title, level: row.level })), ...accidents.map((row) => ({ id: row.id, longitude: row.longitude, latitude: row.latitude, weight: 10, kind: 'ACCIDENT', title: row.title, level: row.level })), ...violations.map((row) => ({ id: row.id, longitude: row.longitude, latitude: row.latitude, weight: 6, kind: 'VIOLATION', title: row.title, level: row.level }))].filter((row) => Number.isFinite(row.longitude) && Number.isFinite(row.latitude));
    return { period: { from, to }, kpis: { alerts: alerts.length, openAlerts: alerts.filter((x) => x.status !== 'CLOSED').length, accidents: accidents.length, violations: violations.length, critical: [...alerts, ...accidents, ...violations].filter((x) => x.level === 'CRITICAL').length, closureRate: this.round(alerts.length ? alerts.filter((x) => x.status === 'CLOSED').length / alerts.length * 100 : 100) }, trend: [...trend.values()], types: [...typeMap].map(([name, value]) => ({ name, value })).sort((a, b) => b.value - a.value), enterprises: [...enterpriseMap.values()].sort((a, b) => b.riskScore - a.riskScore), riskPoints };
  }

  async accidentAnalyses(user: AuthUser, query: AnalyticsQueryDto) {
    const where: Prisma.AccidentWhereInput = { ...this.scoped(user), enterpriseId: user.portal === 'ENTERPRISE' ? user.enterpriseId ?? '__none__' : query.enterpriseId, organizationId: query.organizationId, level: query.level, status: query.status, OR: query.q ? [{ businessNo: { contains: query.q } }, { title: { contains: query.q } }, { vehicle: { name: { contains: query.q } } }] : undefined };
    const [total, items] = await this.prisma.$transaction([this.prisma.accident.count({ where }), this.prisma.accident.findMany({ where, ...this.page(query), orderBy: { occurredAt: 'desc' }, include: { enterprise: { select: { id: true, name: true } }, vehicle: { select: { id: true, name: true, businessNo: true } }, reconstruction: { select: { id: true, status: true, analystName: true, updatedAt: true } }, operationRecord: { select: { id: true, businessNo: true } } } })]); return { page: query.page, pageSize: query.pageSize, total, items };
  }

  async accidentAnalysis(user: AuthUser, id: string, windowMinutes: number) {
    const accident = await this.prisma.accident.findFirst({ where: { id, ...this.scoped(user) }, include: { enterprise: true, organization: true, vehicle: true, operationRecord: { include: { trackPoints: { orderBy: { recordedAt: 'asc' } } } }, alert: true, reconstruction: true } });
    if (!accident) throw new NotFoundException('事故不存在或不在当前数据范围内');
    const from = new Date(accident.occurredAt.getTime() - windowMinutes * 60000), to = new Date(accident.occurredAt.getTime() + windowMinutes * 60000);
    const [alerts, violations] = await this.prisma.$transaction([this.prisma.safetyAlert.findMany({ where: { vehicleId: accident.vehicleId, occurredAt: { gte: from, lte: to } }, orderBy: { occurredAt: 'asc' } }), this.prisma.violation.findMany({ where: { vehicleId: accident.vehicleId, occurredAt: { gte: from, lte: to } }, orderBy: { occurredAt: 'asc' } })]);
    const track = accident.operationRecord?.trackPoints.filter((point) => point.recordedAt >= from && point.recordedAt <= to) ?? [];
    return { ...accident, reconstruction: accident.reconstruction ? { ...accident.reconstruction, evidence: JSON.parse(accident.reconstruction.evidenceJson), causes: JSON.parse(accident.reconstruction.causeJson) } : null, window: { from, to, minutes: windowMinutes }, evidence: { track, alerts, violations, operationRecord: accident.operationRecord ? { id: accident.operationRecord.id, businessNo: accident.operationRecord.businessNo, mileage: accident.operationRecord.mileage, avgSpeed: accident.operationRecord.avgSpeed, maxSpeed: accident.operationRecord.maxSpeed, manualTakeovers: accident.operationRecord.manualTakeovers } : null }, summary: { trackPoints: track.length, alerts: alerts.length, violations: violations.length, maxSpeed: track.reduce((max, point) => Math.max(max, point.speed), 0), minBattery: track.reduce((min, point) => Math.min(min, point.battery), 100), takeovers: track.filter((point) => point.autonomousState === 'REMOTE_TAKEOVER').length } };
  }

  async saveReconstruction(user: AuthUser, id: string, dto: SaveReconstructionDto) {
    if (user.portal === 'ENTERPRISE') throw new ForbiddenException('企业账号不能形成监管事故回溯结论'); const analysis = await this.accidentAnalysis(user, id, dto.windowMinutes ?? 30);
    const evidenceJson = JSON.stringify(analysis.summary), causeJson = JSON.stringify({ primaryCause: dto.primaryCause, contributingFactor: dto.contributingFactor });
    const item = await this.prisma.accidentReconstruction.upsert({ where: { accidentId: id }, create: { accidentId: id, enterpriseId: analysis.enterpriseId, organizationId: analysis.organizationId, windowMinutes: dto.windowMinutes ?? 30, evidenceJson, causeJson, conclusion: dto.conclusion, recommendation: dto.recommendation, status: dto.status ?? 'DRAFT', analystId: user.id, analystName: user.displayName, completedAt: dto.status === 'COMPLETED' ? new Date() : undefined }, update: { windowMinutes: dto.windowMinutes, evidenceJson, causeJson, conclusion: dto.conclusion, recommendation: dto.recommendation, status: dto.status, analystId: user.id, analystName: user.displayName, completedAt: dto.status === 'COMPLETED' ? new Date() : undefined } });
    await this.auth.audit(user, 'analytics', 'accidentReconstruction', item.id, dto.status === 'COMPLETED' ? 'COMPLETE' : 'SAVE'); return item;
  }

  async evaluationConfig(user: AuthUser) { return this.prisma.evaluationIndicator.findMany({ where: user.portal === 'ENTERPRISE' ? { status: 'ACTIVE' } : this.isSuper(user) ? {} : { organization: this.organizationRelation(user) }, orderBy: [{ dimension: 'asc' }, { code: 'asc' }], include: { rules: { where: { status: 'ACTIVE' }, orderBy: { orderNo: 'asc' } }, organization: { select: { id: true, name: true } } } }); }
  async updateIndicator(user: AuthUser, id: string, dto: UpdateIndicatorDto) { if (user.portal === 'ENTERPRISE') throw new ForbiddenException('企业账号不能修改评价指标'); const current = await this.prisma.evaluationIndicator.findFirst({ where: { id, ...(this.isSuper(user) ? {} : { organization: this.organizationRelation(user) }) } }); if (!current) throw new NotFoundException('指标不存在或不在当前范围'); const item = await this.prisma.evaluationIndicator.update({ where: { id }, data: dto }); await this.auth.audit(user, 'analytics', 'evaluationIndicator', id, 'UPDATE', dto); return item; }
  async updateRule(user: AuthUser, id: string, dto: UpdateRuleDto) { if (user.portal === 'ENTERPRISE') throw new ForbiddenException('企业账号不能修改评分规则'); const current = await this.prisma.evaluationRule.findFirst({ where: { id, indicator: this.isSuper(user) ? undefined : { organization: this.organizationRelation(user) } } }); if (!current) throw new NotFoundException('评分规则不存在或不在当前范围'); const item = await this.prisma.evaluationRule.update({ where: { id }, data: dto }); await this.auth.audit(user, 'analytics', 'evaluationRule', id, 'UPDATE', dto); return item; }

  private async scoreEnterprise(enterpriseId: string, from: Date, to: Date, indicators: any[]) {
    const [records, alerts, accidents, violations, online, emergency] = await this.prisma.$transaction([
      this.prisma.operationRecord.findMany({ where: { enterpriseId, startedAt: { gte: from, lte: to } } }), this.prisma.safetyAlert.count({ where: { enterpriseId, occurredAt: { gte: from, lte: to } } }), this.prisma.accident.count({ where: { enterpriseId, occurredAt: { gte: from, lte: to } } }), this.prisma.violation.count({ where: { enterpriseId, occurredAt: { gte: from, lte: to } } }), this.prisma.vehicleOnlineDaily.aggregate({ where: { vehicle: { enterpriseId }, metricDate: { gte: from, lte: to } }, _avg: { onlineRate: true } }), this.prisma.emergencyTask.aggregate({ where: { enterpriseId, closedAt: { gte: from, lte: to } }, _avg: { evaluationScore: true } }),
    ]);
    const mileage = records.reduce((sum, row) => sum + row.mileage, 0), duration = records.reduce((sum, row) => sum + row.durationMinutes, 0) / 60, autonomous = records.reduce((sum, row) => sum + row.autonomousMiles, 0), trips = Math.max(1, records.length);
    const values: Record<string, number> = { alertRate: alerts / trips * 100, accidentCount: accidents, violationCount: violations, onlineRate: online._avg.onlineRate ?? 0, autonomousRate: mileage ? autonomous / mileage * 100 : 0, responseScore: (emergency._avg.evaluationScore ?? 3) * 20, operationEfficiency: duration ? mileage / duration : 0 };
    const breakdown = indicators.map((indicator) => { const value = values[indicator.metricKey] ?? 0; const rule = indicator.rules.find((candidate: any) => (candidate.minValue == null || value >= candidate.minValue) && (candidate.maxValue == null || value < candidate.maxValue)) ?? indicator.rules.at(-1); return { indicatorId: indicator.id, code: indicator.code, name: indicator.name, dimension: indicator.dimension, weight: indicator.weight, value: this.round(value), score: Number(rule?.score ?? 0), rule: rule?.label ?? '无匹配规则' }; });
    const dimensions: Record<string, { weighted: number; weight: number }> = {}; for (const item of breakdown) { dimensions[item.dimension] ??= { weighted: 0, weight: 0 }; dimensions[item.dimension].weighted += item.score * item.weight; dimensions[item.dimension].weight += item.weight; }
    const dimensionScore = (name: string) => this.round(dimensions[name]?.weight ? dimensions[name].weighted / dimensions[name].weight : 0); const total = this.round(breakdown.reduce((sum, item) => sum + item.score * item.weight / 100, 0));
    return { totalScore: total, grade: total >= 90 ? 'A' : total >= 80 ? 'B' : total >= 70 ? 'C' : 'D', riskLevel: total >= 90 ? 'LOW' : total >= 80 ? 'MEDIUM' : total >= 70 ? 'HIGH' : 'CRITICAL', safetyScore: dimensionScore('SAFETY'), complianceScore: dimensionScore('COMPLIANCE'), operationScore: dimensionScore('OPERATION'), breakdown };
  }

  async evaluationTasks(user: AuthUser, query: AnalyticsQueryDto) { if (user.portal === 'ENTERPRISE') throw new ForbiddenException('企业账号不能查看评价任务'); const where: Prisma.EvaluationTaskWhereInput = { ...(this.isSuper(user) ? {} : { organization: this.organizationRelation(user) }), status: query.status, OR: query.q ? [{ businessNo: { contains: query.q } }, { name: { contains: query.q } }] : undefined }; const [total, items] = await this.prisma.$transaction([this.prisma.evaluationTask.count({ where }), this.prisma.evaluationTask.findMany({ where, ...this.page(query), orderBy: { periodEnd: 'desc' }, include: { organization: { select: { id: true, name: true } }, evaluations: { include: { enterprise: { select: { id: true, name: true } } }, orderBy: { totalScore: 'asc' } }, _count: { select: { evaluations: true } } } })]); return { page: query.page, pageSize: query.pageSize, total, items }; }
  async createEvaluationTask(user: AuthUser, dto: CreateEvaluationTaskDto) { if (user.portal === 'ENTERPRISE') throw new ForbiddenException('企业账号不能生成评价任务'); const organizationId = dto.organizationId ?? user.organizationId; if (!organizationId) throw new BadRequestException('请选择评价组织'); const organization = await this.prisma.organization.findFirst({ where: { id: organizationId, ...(this.isSuper(user) ? {} : { OR: [{ id: user.organizationId ?? '__none__' }, { parentId: user.organizationId ?? '__none__' }] }) } }); if (!organization) throw new ForbiddenException('评价组织不在当前范围'); const from = new Date(dto.periodStart), to = new Date(`${dto.periodEnd}T23:59:59.999Z`); const [enterprises, indicators] = await Promise.all([this.prisma.enterprise.findMany({ where: { status: 'ACTIVE', organization: { is: { OR: [{ id: organizationId }, { parentId: organizationId }] } } } }), this.prisma.evaluationIndicator.findMany({ where: { organizationId, status: 'ACTIVE' }, include: { rules: { where: { status: 'ACTIVE' }, orderBy: { orderNo: 'asc' } } } })]); if (!indicators.length) throw new BadRequestException('当前组织尚未配置有效评价指标'); const weight = indicators.reduce((sum, item) => sum + item.weight, 0); if (Math.abs(weight - 100) > .01) throw new BadRequestException(`有效评价指标权重合计应为 100，当前为 ${weight}`); const task = await this.prisma.evaluationTask.create({ data: { businessNo: this.businessNo('EVT'), name: dto.name, periodType: dto.periodType, periodStart: from, periodEnd: to, organizationId, status: 'RUNNING', createdById: user.id, createdByName: user.displayName } }); for (const enterprise of enterprises) { const score = await this.scoreEnterprise(enterprise.id, from, to, indicators); await this.prisma.enterpriseEvaluation.create({ data: { businessNo: this.businessNo('EVA'), taskId: task.id, enterpriseId: enterprise.id, organizationId: enterprise.organizationId, totalScore: score.totalScore, grade: score.grade, riskLevel: score.riskLevel, safetyScore: score.safetyScore, complianceScore: score.complianceScore, operationScore: score.operationScore, breakdownJson: JSON.stringify(score.breakdown), conclusion: `${enterprise.name}本周期综合评价为 ${score.grade} 级，风险等级 ${score.riskLevel}。` } }); } const item = await this.prisma.evaluationTask.update({ where: { id: task.id }, data: { status: 'COMPLETED', generatedAt: new Date() } }); await this.auth.audit(user, 'analytics', 'evaluationTask', item.id, 'GENERATE', { enterprises: enterprises.length }); return item; }
  async publishEvaluationTask(user: AuthUser, id: string) { if (user.portal === 'ENTERPRISE') throw new ForbiddenException('企业账号不能发布评价'); const task = await this.prisma.evaluationTask.findFirst({ where: { id, ...(this.isSuper(user) ? {} : { organization: this.organizationRelation(user) }) } }); if (!task) throw new NotFoundException('评价任务不存在或不在当前范围'); if (task.status !== 'COMPLETED') throw new BadRequestException('仅已计算完成的任务可以发布'); const now = new Date(); await this.prisma.$transaction([this.prisma.evaluationTask.update({ where: { id }, data: { status: 'PUBLISHED', publishedAt: now } }), this.prisma.enterpriseEvaluation.updateMany({ where: { taskId: id }, data: { status: 'PUBLISHED', publishedAt: now } })]); await this.auth.audit(user, 'analytics', 'evaluationTask', id, 'PUBLISH'); return { published: true }; }
  async evaluations(user: AuthUser, query: AnalyticsQueryDto) {
    const where: Prisma.EnterpriseEvaluationWhereInput = { ...this.scoped(user), enterpriseId: user.portal === 'ENTERPRISE' ? user.enterpriseId ?? '__none__' : query.enterpriseId, status: user.portal === 'ENTERPRISE' ? 'PUBLISHED' : query.status, riskLevel: query.level, OR: query.q ? [{ businessNo: { contains: query.q } }, { enterprise: { name: { contains: query.q } } }, { task: { name: { contains: query.q } } }] : undefined };
    const [total, items] = await this.prisma.$transaction([
      this.prisma.enterpriseEvaluation.count({ where }),
      this.prisma.enterpriseEvaluation.findMany({ where, ...this.page(query), orderBy: [{ task: { periodEnd: 'desc' } }, { createdAt: 'desc' }], include: { enterprise: { select: { id: true, name: true } }, task: { select: { id: true, name: true, periodType: true, periodStart: true, periodEnd: true, status: true } }, appeals: { orderBy: { createdAt: 'desc' }, take: 1 } } }),
    ]);
    return { page: query.page, pageSize: query.pageSize, total, items };
  }
  async evaluation(user: AuthUser, id: string) { const item = await this.prisma.enterpriseEvaluation.findFirst({ where: { id, ...this.scoped(user), ...(user.portal === 'ENTERPRISE' ? { status: 'PUBLISHED' } : {}) }, include: { enterprise: true, organization: true, task: true, appeals: { orderBy: { createdAt: 'desc' } } } }); if (!item) throw new NotFoundException('评价结果不存在或不在当前数据范围内'); return { ...item, breakdown: JSON.parse(item.breakdownJson), breakdownJson: undefined }; }
  async createAppeal(user: AuthUser, id: string, dto: CreateAppealDto) { if (user.portal !== 'ENTERPRISE') throw new ForbiddenException('仅企业账号可以提交评价申诉'); const evaluation = await this.prisma.enterpriseEvaluation.findFirst({ where: { id, enterpriseId: user.enterpriseId ?? '__none__', status: 'PUBLISHED' } }); if (!evaluation) throw new NotFoundException('可申诉评价结果不存在'); const open = await this.prisma.evaluationAppeal.findFirst({ where: { evaluationId: id, status: 'SUBMITTED' } }); if (open) throw new BadRequestException('该评价已有待复核申诉'); const item = await this.prisma.evaluationAppeal.create({ data: { businessNo: this.businessNo('APL'), evaluationId: id, enterpriseId: evaluation.enterpriseId, organizationId: evaluation.organizationId, reason: dto.reason, evidence: dto.evidence, submittedById: user.id, submittedByName: user.displayName } }); await this.auth.audit(user, 'analytics', 'evaluationAppeal', item.id, 'SUBMIT'); return item; }
  async appeals(user: AuthUser, query: AnalyticsQueryDto) { const where: Prisma.EvaluationAppealWhereInput = { ...this.scoped(user), enterpriseId: user.portal === 'ENTERPRISE' ? user.enterpriseId ?? '__none__' : query.enterpriseId, status: query.status, OR: query.q ? [{ businessNo: { contains: query.q } }, { enterprise: { name: { contains: query.q } } }] : undefined }; const [total, items] = await this.prisma.$transaction([this.prisma.evaluationAppeal.count({ where }), this.prisma.evaluationAppeal.findMany({ where, ...this.page(query), orderBy: { createdAt: 'desc' }, include: { enterprise: { select: { id: true, name: true } }, evaluation: { include: { task: { select: { name: true, periodStart: true, periodEnd: true } } } } } })]); return { page: query.page, pageSize: query.pageSize, total, items }; }
  async reviewAppeal(user: AuthUser, id: string, dto: ReviewAppealDto) { if (user.portal === 'ENTERPRISE') throw new ForbiddenException('企业账号不能复核申诉'); const current = await this.prisma.evaluationAppeal.findFirst({ where: { id, ...(this.isSuper(user) ? {} : { organization: this.organizationRelation(user) }) } }); if (!current) throw new NotFoundException('申诉不存在或不在当前范围'); if (current.status !== 'SUBMITTED') throw new BadRequestException('该申诉已完成复核'); const status = dto.action === 'ACCEPT' ? 'ACCEPTED' : 'REJECTED'; const item = await this.prisma.$transaction(async (tx) => { const appeal = await tx.evaluationAppeal.update({ where: { id }, data: { status, reviewerId: user.id, reviewerName: user.displayName, reviewComment: dto.comment, reviewedAt: new Date() } }); if (status === 'ACCEPTED') await tx.enterpriseEvaluation.update({ where: { id: current.evaluationId }, data: { status: 'UNDER_REVIEW', conclusion: `原评价因申诉受理进入重新核定：${dto.comment}` } }); return appeal; }); await this.auth.audit(user, 'analytics', 'evaluationAppeal', id, dto.action); return item; }

  async profiles(user: AuthUser, query: AnalyticsQueryDto) { const where: Prisma.EnterpriseWhereInput = { ...this.enterpriseScoped(user), id: user.portal === 'ENTERPRISE' ? user.enterpriseId ?? '__none__' : query.enterpriseId, status: 'ACTIVE', name: query.q ? { contains: query.q } : undefined }; const all = await this.prisma.enterprise.findMany({ where, orderBy: { name: 'asc' } }); const items = await Promise.all(all.map((item) => this.profile(user, item.id))); return { page: 1, pageSize: items.length, total: items.length, items }; }
  async profile(user: AuthUser, enterpriseId: string) { const enterprise = await this.assertEnterprise(user, enterpriseId); const [evaluation, vehicleCount, alerts, accidents, violations, offline, records] = await this.prisma.$transaction([this.prisma.enterpriseEvaluation.findFirst({ where: { enterpriseId, status: { in: ['PUBLISHED', 'UNDER_REVIEW'] } }, orderBy: { publishedAt: 'desc' }, include: { task: true } }), this.prisma.vehicle.count({ where: { enterpriseId, deletedAt: null } }), this.prisma.safetyAlert.count({ where: { enterpriseId } }), this.prisma.accident.count({ where: { enterpriseId } }), this.prisma.violation.count({ where: { enterpriseId } }), this.prisma.offlineEvent.count({ where: { enterpriseId } }), this.prisma.operationRecord.aggregate({ where: { enterpriseId }, _sum: { mileage: true, autonomousMiles: true } })]); const mileage = records._sum.mileage ?? 0; const dimensions = evaluation ? { safety: evaluation.safetyScore, compliance: evaluation.complianceScore, operation: evaluation.operationScore, onlineStability: Math.max(0, 100 - offline * 4), emergencyResponse: Math.max(0, 100 - alerts * 2), autonomy: this.round(mileage ? (records._sum.autonomousMiles ?? 0) / mileage * 100 : 0) } : null; const tags = [accidents > 1 ? '事故风险偏高' : '事故控制稳定', violations > 1 ? '合规整改重点' : '合规表现稳定', offline > 1 ? '联网稳定性待提升' : '联网稳定', evaluation?.riskLevel === 'CRITICAL' ? '重点监管' : evaluation?.grade === 'A' ? '示范企业' : '常规监管']; return { enterprise, evaluation: evaluation ? { ...evaluation, breakdown: JSON.parse(evaluation.breakdownJson), breakdownJson: undefined } : null, metrics: { vehicleCount, alerts, accidents, violations, offline, mileage: this.round(mileage) }, dimensions, tags }; }

  async reports(user: AuthUser, query: AnalyticsQueryDto) { const where: Prisma.RegulatoryReportWhereInput = { ...this.scoped(user), enterpriseId: user.portal === 'ENTERPRISE' ? user.enterpriseId ?? '__none__' : query.enterpriseId, category: query.type, status: query.status, OR: query.q ? [{ businessNo: { contains: query.q } }, { title: { contains: query.q } }] : undefined }; const [total, items] = await this.prisma.$transaction([this.prisma.regulatoryReport.count({ where }), this.prisma.regulatoryReport.findMany({ where, ...this.page(query), orderBy: { generatedAt: 'desc' }, include: { enterprise: { select: { id: true, name: true } }, organization: { select: { id: true, name: true } } } })]); return { page: query.page, pageSize: query.pageSize, total, items }; }
  async report(user: AuthUser, id: string) { const item = await this.prisma.regulatoryReport.findFirst({ where: { id, ...this.scoped(user) }, include: { enterprise: true, organization: true } }); if (!item) throw new NotFoundException('报表不存在或不在当前数据范围内'); return { ...item, summary: JSON.parse(item.summaryJson), summaryJson: undefined }; }
  async createReport(user: AuthUser, dto: CreateReportDto) { if (user.portal === 'ENTERPRISE' && dto.enterpriseId && dto.enterpriseId !== user.enterpriseId) throw new ForbiddenException('不能生成其他企业报表'); const enterpriseId = user.portal === 'ENTERPRISE' ? user.enterpriseId ?? undefined : dto.enterpriseId; if (enterpriseId) await this.assertEnterprise(user, enterpriseId); const query = Object.assign(new AnalyticsQueryDto(), { from: dto.periodStart, to: dto.periodEnd, enterpriseId }); const [operations, safety] = await Promise.all([this.operationAnalysis(user, query), this.safetyAnalysis(user, query)]); const organizationId = enterpriseId ? (await this.prisma.enterprise.findUniqueOrThrow({ where: { id: enterpriseId } })).organizationId : user.organizationId; if (!organizationId) throw new BadRequestException('当前账号缺少组织归属'); const summary = dto.category === 'OPERATIONS' ? { operations } : dto.category === 'SAFETY' ? { safety } : { operations, safety }; const item = await this.prisma.regulatoryReport.create({ data: { businessNo: this.businessNo('RPT'), reportType: dto.reportType, category: dto.category, title: dto.title, periodStart: new Date(dto.periodStart), periodEnd: new Date(`${dto.periodEnd}T23:59:59.999Z`), enterpriseId, organizationId, summaryJson: JSON.stringify(summary), recipient: dto.recipient, generatedById: user.id, generatedByName: user.displayName } }); await this.auth.audit(user, 'analytics', 'regulatoryReport', item.id, 'GENERATE', { businessNo: item.businessNo }); return item; }
  async updateReport(user: AuthUser, id: string, dto: UpdateReportDto) { const current = await this.prisma.regulatoryReport.findFirst({ where: { id, ...this.scoped(user) } }); if (!current) throw new NotFoundException('报表不存在或不在当前范围'); const item = await this.prisma.regulatoryReport.update({ where: { id }, data: { recipient: dto.recipient, status: dto.status, distributedAt: dto.status === 'DISTRIBUTED' ? new Date() : undefined } }); await this.auth.audit(user, 'analytics', 'regulatoryReport', id, dto.status === 'DISTRIBUTED' ? 'DISTRIBUTE' : 'UPDATE'); return item; }
  async exportReport(user: AuthUser, id: string) { const item = await this.report(user, id); const rows: Array<[string, string | number]> = [['报表编号', item.businessNo], ['报表名称', item.title], ['报表类型', item.reportType], ['统计周期', `${this.dateKey(item.periodStart)} 至 ${this.dateKey(item.periodEnd)}`], ['生成机构', item.organization.name], ['生成时间', item.generatedAt.toISOString()]]; const operations = item.summary.operations?.kpis, safety = item.summary.safety?.kpis; if (operations) rows.push(['运行车辆数', operations.vehicles], ['运行次数', operations.trips], ['运行里程(km)', operations.mileage], ['运行时长(h)', operations.durationHours], ['自主运行率(%)', operations.autonomousRate]); if (safety) rows.push(['告警数', safety.alerts], ['事故数', safety.accidents], ['违规数', safety.violations], ['告警闭环率(%)', safety.closureRate]); const escape = (value: string | number) => `"${String(value).replace(/"/g, '""')}"`; return { filename: `${item.businessNo}.csv`, mimeType: 'text/csv;charset=utf-8', content: `\ufeff指标,数值\r\n${rows.map((row) => row.map(escape).join(',')).join('\r\n')}` }; }
}
