<script setup lang="ts">
import { computed, onMounted, reactive, ref, watch } from 'vue';
import { Edit3, MapPinned, Plus, RefreshCw, Search } from 'lucide-vue-next';
import { ElMessage } from 'element-plus';
import { api } from '../api';
import OperationsMap from '../components/OperationsMap.vue';
import PageHeader from '../components/PageHeader.vue';
import type { ElectronicFenceItem, PageData } from '../types';
const loading=ref(false),saving=ref(false),error=ref(''),rows=ref<ElectronicFenceItem[]>([]),total=ref(0),page=ref(1),q=ref(''),type=ref(''),status=ref(''),enterpriseId=ref(''),selectedId=ref(''),dialog=ref(false),editingId=ref(''),draftMap=ref<any>(null);const options=reactive<any>({vehicles:[],enterprises:[],organizations:[]});const form=reactive({businessNo:'',name:'',fenceType:'NO_ENTRY',enterpriseId:'',organizationId:'',validFrom:'',validTo:'',active:false,speedLimit:10,allowedHours:'00:00-24:00',ruleDescription:'',vehicleIds:[] as string[],polygonText:''});const selected=computed(()=>rows.value.find(item=>item.id===selectedId.value)??rows.value[0]);const vehicleOptions=computed(()=>options.vehicles.filter((item:any)=>!form.enterpriseId||item.enterpriseId===form.enterpriseId));let timer:number|undefined;const typeText=(v:string)=>({NO_ENTRY:'禁行区',SPEED_LIMIT:'限速区',OPERATION:'运营区',TEMPORARY:'临时管制区'}as any)[v]??v;const date=(v?:string|null)=>v?.slice(0,10)??'';
async function loadOptions(){Object.assign(options,await api<any>('/safety/options'))}async function load(){loading.value=true;error.value='';try{const p=new URLSearchParams({page:String(page.value),pageSize:'50'});if(q.value)p.set('q',q.value);if(type.value)p.set('type',type.value);if(status.value)p.set('status',status.value);if(enterpriseId.value)p.set('enterpriseId',enterpriseId.value);const data=await api<PageData<ElectronicFenceItem>>(`/safety/fences?${p}`);rows.value=data.items;total.value=data.total;if(!rows.value.some(item=>item.id===selectedId.value))selectedId.value=rows.value[0]?.id??''}catch(reason){error.value=reason instanceof Error?reason.message:'电子围栏加载失败'}finally{loading.value=false}}watch([q,type,status,enterpriseId],()=>{page.value=1;clearTimeout(timer);timer=window.setTimeout(load,180)});watch(page,load);onMounted(()=>Promise.all([load(),loadOptions()]));
function openForm(row?:ElectronicFenceItem){editingId.value=row?.id??'';Object.assign(form,row?{businessNo:row.businessNo,name:row.name,fenceType:row.fenceType,enterpriseId:row.enterpriseId??'',organizationId:row.organizationId,validFrom:date(row.validFrom),validTo:date(row.validTo),active:row.active,speedLimit:row.speedLimit??10,allowedHours:row.allowedHours??'',ruleDescription:row.ruleDescription??'',vehicleIds:row.vehicles.map(item=>item.vehicle.id),polygonText:row.polygon.map(point=>`${point.longitude},${point.latitude}`).join('\n')}:{businessNo:`FENCE-${new Date().getFullYear()}-`,name:'',fenceType:'NO_ENTRY',enterpriseId:'',organizationId:options.organizations[0]?.id??'',validFrom:date(new Date().toISOString()),validTo:'',active:false,speedLimit:10,allowedHours:'00:00-24:00',ruleDescription:'',vehicleIds:[],polygonText:''});dialog.value=true}
function polygon(){const result=form.polygonText.split(/\r?\n/).map(line=>line.split(',').map(Number)).filter(pair=>pair.length===2&&pair.every(Number.isFinite)).map(([longitude,latitude])=>({longitude,latitude}));if(result.length<3)throw new Error('请在地图绘制或填写至少 3 个有效坐标点');return result}
function startDraw(){if(!draftMap.value?.startPolygonDraw())ElMessage.warning('地图尚未就绪');else ElMessage.info('请在地图上逐点单击，双击完成围栏绘制')}
function drawn(points:Array<{longitude:number;latitude:number}>){form.polygonText=points.map(point=>`${point.longitude.toFixed(6)},${point.latitude.toFixed(6)}`).join('\n');ElMessage.success(`已读取 ${points.length} 个围栏顶点`)}
async function save(){if(!form.businessNo||!form.name||!form.organizationId||!form.validFrom)return ElMessage.warning('请填写围栏编号、名称、管理机构和生效日期');saving.value=true;try{const payload:any={...form,enterpriseId:form.enterpriseId||undefined,validTo:form.validTo||undefined,polygon:polygon()};delete payload.polygonText;if(form.fenceType!=='SPEED_LIMIT')delete payload.speedLimit;await api(editingId.value?`/safety/fences/${editingId.value}`:'/safety/fences',{method:editingId.value?'PATCH':'POST',body:JSON.stringify(payload)});ElMessage.success(editingId.value?'电子围栏已保存':'电子围栏已创建');dialog.value=false;await load()}catch(reason){ElMessage.error(reason instanceof Error?reason.message:'保存失败')}finally{saving.value=false}}
async function toggle(row:ElectronicFenceItem){try{await api(`/safety/fences/${row.id}/status`,{method:'PATCH',body:JSON.stringify({active:!row.active})});ElMessage.success(row.active?'围栏已停用':'围栏已启用');await load()}catch(reason){ElMessage.error(reason instanceof Error?reason.message:'状态更新失败')}}
</script>
<template><PageHeader title="电子围栏" description="独立维护禁行、限速、运营与临时管制规则；车辆触发后统一进入告警中心。" :count="total"><el-button :icon="RefreshCw" :loading="loading" @click="load">刷新</el-button><el-button type="primary" :icon="Plus" @click="openForm()">新建围栏</el-button></PageHeader><div class="table-toolbar operation-toolbar"><el-input v-model="q" :prefix-icon="Search" clearable placeholder="搜索围栏编号、名称或企业"/><el-select v-model="type" clearable placeholder="全部围栏类型"><el-option v-for="item in ['NO_ENTRY','SPEED_LIMIT','OPERATION','TEMPORARY']" :key="item" :label="typeText(item)" :value="item"/></el-select><el-select v-model="status" clearable placeholder="全部状态"><el-option label="已启用" value="ACTIVE"/><el-option label="已停用" value="INACTIVE"/></el-select><el-select v-model="enterpriseId" clearable filterable placeholder="全部企业"><el-option v-for="item in options.enterprises" :key="item.id" :label="item.name" :value="item.id"/></el-select></div><div v-if="error" class="error-state"><strong>电子围栏暂时无法加载</strong><span>{{error}}</span><el-button @click="load">重试</el-button></div><div v-else class="fence-workspace"><OperationsMap mode="fences" :fences="rows" :selected-id="selected?.id" height="620px" @fence-select="selectedId=$event"/><aside class="fence-rail"><button v-for="row in rows" :key="row.id" :class="{active:selected?.id===row.id}" @click="selectedId=row.id"><i :class="row.fenceType.toLowerCase().replace('_','-')"></i><span><strong>{{row.name}}</strong><small>{{row.businessNo}} · {{row.enterprise?.name||'公共围栏'}}</small></span><el-tag size="small" :type="row.active?'success':'info'">{{row.active?'已启用':'已停用'}}</el-tag></button></aside></div><section v-if="selected" class="region-detail fence-detail"><header><div><span>{{selected.businessNo}}</span><h2>{{selected.name}}</h2></div><div><el-button :icon="Edit3" @click="openForm(selected)">编辑</el-button><el-button :type="selected.active?'danger':'primary'" plain @click="toggle(selected)">{{selected.active?'停用围栏':'启用围栏'}}</el-button></div></header><dl class="selected-data"><div><dt>围栏类型</dt><dd>{{typeText(selected.fenceType)}}</dd></div><div><dt>关联企业</dt><dd>{{selected.enterprise?.name||'跨企业公共规则'}}</dd></div><div><dt>关联车辆</dt><dd>{{selected.vehicles.length?`${selected.vehicles.length} 辆`:'范围内全部车辆'}}</dd></div><div><dt>累计触发</dt><dd>{{selected._count.triggers}} 次</dd></div><div><dt>生效时间</dt><dd>{{date(selected.validFrom)}} 至 {{date(selected.validTo)||'长期'}}</dd></div><div><dt>限速 / 时段</dt><dd>{{selected.speedLimit?`${selected.speedLimit} km/h · `:''}}{{selected.allowedHours||'全天'}}</dd></div><div class="detail-span-2"><dt>规则说明</dt><dd>{{selected.ruleDescription||'—'}}</dd></div></dl></section>
<el-dialog v-model="dialog" :title="editingId?'编辑电子围栏':'新建电子围栏'" width="900px" destroy-on-close><div class="fence-editor"><section><div class="map-editor-toolbar"><div><MapPinned :size="16"/><span>地图绘制</span></div><el-button size="small" @click="startDraw">开始绘制</el-button></div><OperationsMap ref="draftMap" mode="fences" :fences="[]" height="360px" @polygon-drawn="drawn"/></section><div class="form-grid"><el-form-item label="围栏编号" required><el-input v-model.trim="form.businessNo"/></el-form-item><el-form-item label="围栏名称" required><el-input v-model.trim="form.name"/></el-form-item><el-form-item label="围栏类型"><el-select v-model="form.fenceType"><el-option v-for="item in ['NO_ENTRY','SPEED_LIMIT','OPERATION','TEMPORARY']" :key="item" :label="typeText(item)" :value="item"/></el-select></el-form-item><el-form-item label="管理机构" required><el-select v-model="form.organizationId"><el-option v-for="item in options.organizations" :key="item.id" :label="item.name" :value="item.id"/></el-select></el-form-item><el-form-item label="关联企业"><el-select v-model="form.enterpriseId" clearable filterable @change="form.vehicleIds=[]"><el-option v-for="item in options.enterprises" :key="item.id" :label="item.name" :value="item.id"/></el-select></el-form-item><el-form-item label="关联车辆"><el-select v-model="form.vehicleIds" multiple collapse-tags filterable><el-option v-for="item in vehicleOptions" :key="item.id" :label="`${item.name} · ${item.businessNo}`" :value="item.id"/></el-select></el-form-item><el-form-item label="生效日期" required><el-date-picker v-model="form.validFrom" type="date" value-format="YYYY-MM-DD"/></el-form-item><el-form-item label="失效日期"><el-date-picker v-model="form.validTo" type="date" value-format="YYYY-MM-DD"/></el-form-item><el-form-item v-if="form.fenceType==='SPEED_LIMIT'" label="限速值 (km/h)" required><el-input-number v-model="form.speedLimit" :min="1" :max="80"/></el-form-item><el-form-item label="生效时段"><el-input v-model.trim="form.allowedHours"/></el-form-item><el-form-item class="form-span-2" label="边界坐标" required><el-input v-model="form.polygonText" type="textarea" :rows="4" placeholder="可从地图绘制自动生成；也可每行填写 经度,纬度"/></el-form-item><el-form-item class="form-span-2" label="规则说明"><el-input v-model.trim="form.ruleDescription" type="textarea" :rows="3"/></el-form-item></div></div><template #footer><el-button @click="dialog=false">取消</el-button><el-button type="primary" :loading="saving" @click="save">保存围栏</el-button></template></el-dialog></template>
