<script setup lang="ts">
import { computed, onMounted, reactive, ref, watch } from 'vue';
import { ElMessage } from 'element-plus';
import { Building2, RefreshCw, Save, Search } from 'lucide-vue-next';
import { api } from '../api';
import PageHeader from '../components/PageHeader.vue';
import { useSessionStore } from '../stores/session';
import type { PageData } from '../types';

const session=useSessionStore(),isEnterprise=computed(()=>session.user?.portal==='ENTERPRISE'),canWrite=computed(()=>session.user?.permissions.includes('archive:enterprise-archive:write'));
const rows=ref<any[]>([]),total=ref(0),loading=ref(false),error=ref(''),q=ref(''),status=ref(''),page=ref(1),pageSize=20,detail=ref<any>(null),drawer=ref(false),editing=ref(false),saving=ref(false);
const form=reactive({legalRepresentative:'',contactName:'',contactPhone:'',registeredAddress:''});let timer:number|undefined;
const date=(value?:string)=>value?new Date(value).toLocaleDateString('zh-CN'):'—';
async function load(){loading.value=true;error.value='';try{if(isEnterprise.value){detail.value=await api<any>('/archives/enterprises/current');total.value=1}else{const p=new URLSearchParams({page:String(page.value),pageSize:String(pageSize),sort:'updatedAt',order:'desc'});if(q.value)p.set('q',q.value);if(status.value)p.set('status',status.value);const data=await api<PageData<any>>(`/archives/enterprises?${p}`);rows.value=data.items;total.value=data.total}}catch(reason){error.value=reason instanceof Error?reason.message:'企业档案加载失败'}finally{loading.value=false}}
watch([q,status],()=>{page.value=1;clearTimeout(timer);timer=window.setTimeout(load,180)});watch(page,load);onMounted(load);
async function open(row:any){drawer.value=true;loading.value=true;try{detail.value=await api<any>(`/archives/enterprises/${row.id}`)}catch(reason){ElMessage.error(reason instanceof Error?reason.message:'档案加载失败');drawer.value=false}finally{loading.value=false}}
function startEdit(){Object.assign(form,{legalRepresentative:detail.value.legalRepresentative??'',contactName:detail.value.contactName??'',contactPhone:detail.value.contactPhone??'',registeredAddress:detail.value.registeredAddress??''});editing.value=true}
async function save(){saving.value=true;try{const path=isEnterprise.value?'/archives/enterprises/current':`/archives/enterprises/${detail.value.id}`;await api(path,{method:'PATCH',body:JSON.stringify(form)});ElMessage.success('企业档案已保存');editing.value=false;detail.value=await api<any>(isEnterprise.value?'/archives/enterprises/current':`/archives/enterprises/${detail.value.id}`);if(!isEnterprise.value)await load()}catch(reason){ElMessage.error(reason instanceof Error?reason.message:'保存失败')}finally{saving.value=false}}
</script>
<template>
  <PageHeader :title="isEnterprise?'企业信息':'企业档案'" :description="isEnterprise?'维护企业法定代表人、联系人和注册地址。':'查看企业主体、运营规模、资质与监管归属。'" :count="isEnterprise?undefined:total"><el-button v-if="!isEnterprise" :icon="RefreshCw" @click="load">刷新</el-button><el-button v-if="isEnterprise&&canWrite&&!editing" type="primary" @click="startEdit">编辑企业信息</el-button></PageHeader>
  <div v-if="error" class="error-state"><strong>企业档案暂时无法加载</strong><span>{{error}}</span><el-button @click="load">重试</el-button></div>
  <template v-else-if="isEnterprise">
    <div v-loading="loading" class="profile-sheet" v-if="detail"><div class="profile-heading"><div class="profile-emblem"><Building2 :size="24"/></div><div><h2>{{detail.name}}</h2><span>{{detail.businessNo}} · {{detail.creditCode}}</span></div><span class="status-mark" :class="detail.status.toLowerCase()"><i></i>{{detail.status==='ACTIVE'?'正常运营':'已停用'}}</span></div>
      <template v-if="editing"><div class="form-grid profile-form"><el-form-item label="法定代表人"><el-input v-model="form.legalRepresentative"/></el-form-item><el-form-item label="业务联系人"><el-input v-model="form.contactName"/></el-form-item><el-form-item label="联系电话"><el-input v-model="form.contactPhone"/></el-form-item><el-form-item label="注册地址"><el-input v-model="form.registeredAddress"/></el-form-item></div><div class="profile-actions"><el-button @click="editing=false">取消</el-button><el-button type="primary" :icon="Save" :loading="saving" @click="save">保存更改</el-button></div></template>
      <dl v-else class="detail-grid profile-details"><div><dt>企业类型</dt><dd>{{detail.type==='OPERATOR'?'运营企业':detail.type}}</dd></div><div><dt>监管机构</dt><dd>{{detail.organization.name}}</dd></div><div><dt>法定代表人</dt><dd>{{detail.legalRepresentative||'—'}}</dd></div><div><dt>业务联系人</dt><dd>{{detail.contactName||'—'}} {{detail.contactPhone||''}}</dd></div><div class="detail-span-2"><dt>注册地址</dt><dd>{{detail.registeredAddress||'—'}}</dd></div><div><dt>在册车辆</dt><dd>{{detail._count.vehicles}} 辆</dd></div><div><dt>企业账号</dt><dd>{{detail._count.users}} 个</dd></div></dl>
    </div>
  </template>
  <template v-else>
    <div class="table-toolbar"><el-input v-model="q" :prefix-icon="Search" clearable placeholder="搜索企业、编号或信用代码" aria-label="搜索企业档案"/><el-select v-model="status" clearable placeholder="全部状态" aria-label="企业状态"><el-option label="正常" value="ACTIVE"/><el-option label="停用" value="INACTIVE"/></el-select><el-button v-if="q||status" text @click="q='';status=''">清除筛选</el-button></div>
    <el-table v-loading="loading" :data="rows" empty-text="暂无符合条件的企业档案" @row-click="open"><el-table-column label="企业" min-width="250"><template #default="{row}"><button class="table-link" @click.stop="open(row)"><strong>{{row.name}}</strong><span>{{row.businessNo}}</span></button></template></el-table-column><el-table-column label="统一社会信用代码" prop="creditCode" min-width="190"/><el-table-column label="监管机构" min-width="170"><template #default="{row}">{{row.organization.name}}</template></el-table-column><el-table-column label="在册车辆" width="100"><template #default="{row}">{{row._count.vehicles}}</template></el-table-column><el-table-column label="有效资质" width="100"><template #default="{row}">{{row._count.qualifications}}</template></el-table-column><el-table-column label="账号" width="80"><template #default="{row}">{{row._count.users}}</template></el-table-column><el-table-column label="状态" width="90"><template #default="{row}"><span class="status-mark" :class="row.status.toLowerCase()"><i></i>{{row.status==='ACTIVE'?'正常':'停用'}}</span></template></el-table-column></el-table>
    <div class="pagination-row"><span>当前显示 {{rows.length}} / {{total}}</span><el-pagination v-model:current-page="page" :page-size="pageSize" :total="total" layout="prev, pager, next"/></div>
  </template>
  <el-drawer v-if="!isEnterprise" v-model="drawer" size="680px"><template #header><div v-if="detail" class="archive-drawer-title"><div><span>{{detail.businessNo}}</span><h2>{{detail.name}}</h2></div><el-button v-if="canWrite&&!editing" @click="startEdit">编辑档案</el-button></div></template><div v-if="detail"><template v-if="editing"><div class="form-grid"><el-form-item label="法定代表人"><el-input v-model="form.legalRepresentative"/></el-form-item><el-form-item label="业务联系人"><el-input v-model="form.contactName"/></el-form-item><el-form-item label="联系电话"><el-input v-model="form.contactPhone"/></el-form-item><el-form-item label="注册地址"><el-input v-model="form.registeredAddress"/></el-form-item></div><div class="profile-actions"><el-button @click="editing=false">取消</el-button><el-button type="primary" :loading="saving" @click="save">保存档案</el-button></div></template><template v-else><dl class="detail-grid"><div><dt>统一社会信用代码</dt><dd>{{detail.creditCode}}</dd></div><div><dt>监管机构</dt><dd>{{detail.organization.name}}</dd></div><div><dt>法定代表人</dt><dd>{{detail.legalRepresentative||'—'}}</dd></div><div><dt>业务联系人</dt><dd>{{detail.contactName||'—'}} {{detail.contactPhone||''}}</dd></div><div class="detail-span-2"><dt>注册地址</dt><dd>{{detail.registeredAddress||'—'}}</dd></div></dl><div class="metric-strip archive-metrics"><div><span>在册车辆</span><strong>{{detail._count.vehicles}}</strong></div><div><span>企业账号</span><strong>{{detail._count.users}}</strong></div><div><span>资质记录</span><strong>{{detail.qualifications.length}}</strong></div></div><div class="subsection-title"><strong>企业资质</strong><span>按到期时间排序</span></div><el-table :data="detail.qualifications" empty-text="暂无企业资质"><el-table-column label="资质类型" prop="qualificationType"/><el-table-column label="证书编号" prop="certificateNo"/><el-table-column label="有效期至"><template #default="{row}">{{date(row.expiresAt)}}</template></el-table-column><el-table-column label="状态"><template #default="{row}">{{row.status==='VALID'?'有效':'异常'}}</template></el-table-column></el-table></template></div></el-drawer>
</template>
