<script setup lang="ts">
import { computed, onMounted, reactive, ref } from 'vue';
import { AlertTriangle, BadgeCheck, RefreshCw, ShieldAlert, ShieldX, Siren } from 'lucide-vue-next';
import { api } from '../api';
import AnalyticsChart from '../components/AnalyticsChart.vue';
import OperationsMap from '../components/OperationsMap.vue';
import PageHeader from '../components/PageHeader.vue';
import type { AnalyticsOptions, SafetyAnalysis } from '../types';
const loading=ref(false),error=ref('');const options=reactive<AnalyticsOptions>({enterprises:[],organizations:[],vehicles:[],accidents:[]});const data=ref<SafetyAnalysis|null>(null);const filters=reactive({dates:[new Date(Date.now()-29*86400000).toISOString().slice(0,10),new Date().toISOString().slice(0,10)],enterpriseId:'',organizationId:''});
const axis={axisLine:{lineStyle:{color:'#dfe3e8'}},axisLabel:{fontSize:10}};const trendOption=computed(()=>({tooltip:{trigger:'axis'},legend:{top:0,right:0},grid:{left:40,right:18,top:34,bottom:28},xAxis:{type:'category',data:data.value?.trend.map(x=>x.date.slice(5)),...axis},yAxis:{type:'value',splitLine:{lineStyle:{color:'#edf0f2'}},axisLabel:{fontSize:10}},series:[{name:'告警',type:'line',smooth:true,data:data.value?.trend.map(x=>x.alerts),itemStyle:{color:'#d97706'}},{name:'事故',type:'line',smooth:true,data:data.value?.trend.map(x=>x.accidents),itemStyle:{color:'#b91c1c'}},{name:'违规',type:'line',smooth:true,data:data.value?.trend.map(x=>x.violations),itemStyle:{color:'#6b7280'}}]}));
const eventTypeText=(value:string)=>({OVERSPEED:'超速',NO_ENTRY:'闯入禁行区',AUTONOMOUS_ABNORMAL:'自动驾驶异常',VEHICLE_FAULT:'车辆故障',OFFLINE:'车辆离线',PROPERTY_DAMAGE:'财产损失',COLLISION:'碰撞',OUT_OF_BOUNDS:'越界',OVERTIME:'超时运行'} as Record<string,string>)[value.split(':').at(-1)??'']??value;
const typeOption=computed(()=>({tooltip:{trigger:'axis',axisPointer:{type:'shadow'}},grid:{left:126,right:28,top:12,bottom:18},xAxis:{type:'value',splitLine:{lineStyle:{color:'#edf0f2'}},axisLabel:{fontSize:10}},yAxis:{type:'category',inverse:true,data:data.value?.types.slice(0,8).map(x=>eventTypeText(x.name)),axisLabel:{fontSize:9,width:112,overflow:'truncate'}},series:[{type:'bar',barMaxWidth:14,data:data.value?.types.slice(0,8).map((x,i)=>({value:x.value,itemStyle:{color:['#315f91','#d97706','#b91c1c','#6b7280','#7c3aed','#0f766e'][i%6],borderRadius:[0,4,4,0]}})),label:{show:true,position:'right',fontSize:10}}]}));
async function load(){loading.value=true;error.value='';try{const p=new URLSearchParams({from:filters.dates[0],to:filters.dates[1]});if(filters.enterpriseId)p.set('enterpriseId',filters.enterpriseId);if(filters.organizationId)p.set('organizationId',filters.organizationId);data.value=await api<SafetyAnalysis>(`/analytics/safety?${p}`)}catch(e){error.value=e instanceof Error?e.message:'安全态势加载失败'}finally{loading.value=false}}onMounted(async()=>{Object.assign(options,await api<AnalyticsOptions>('/analytics/options'));await load()});
</script>
<template><PageHeader title="安全态势" description="融合告警、事故与违规数据，识别高风险企业和空间聚集区域。"><el-button :icon="RefreshCw" :loading="loading" @click="load">刷新</el-button></PageHeader><section class="phase6-filter"><el-date-picker v-model="filters.dates" type="daterange" value-format="YYYY-MM-DD" range-separator="至" start-placeholder="开始日期" end-placeholder="结束日期"/><el-select v-model="filters.organizationId" clearable placeholder="全部监管机构" style="width:190px"><el-option v-for="x in options.organizations" :key="x.id" :label="x.name" :value="x.id"/></el-select><el-select v-model="filters.enterpriseId" clearable placeholder="全部企业" style="width:210px"><el-option v-for="x in options.enterprises" :key="x.id" :label="x.name" :value="x.id"/></el-select><el-button type="primary" @click="load">查询</el-button></section><div v-if="error" class="error-state"><strong>安全态势暂时无法加载</strong><span>{{error}}</span><el-button @click="load">重试</el-button></div><template v-else><section v-if="data" class="phase6-metrics" v-loading="loading"><article class="phase6-metric"><Siren/><span>安全告警</span><strong>{{data.kpis.alerts}}</strong><small>{{data.kpis.openAlerts}} 条待闭环</small></article><article class="phase6-metric"><ShieldX/><span>事故事件</span><strong>{{data.kpis.accidents}}</strong><small>统计周期</small></article><article class="phase6-metric"><ShieldAlert/><span>违规事件</span><strong>{{data.kpis.violations}}</strong><small>监管认定</small></article><article class="phase6-metric danger"><AlertTriangle/><span>重大风险</span><strong>{{data.kpis.critical}}</strong><small>需优先处置</small></article><article class="phase6-metric"><BadgeCheck/><span>告警闭环率</span><strong>{{data.kpis.closureRate}}%</strong><small>已关闭告警</small></article></section><section class="phase6-map-grid"><article class="phase6-panel"><header><div><strong>风险空间分布</strong><span>热力强度综合事件类型与风险等级</span></div><b>{{data?.riskPoints.length ?? 0}} 个风险点</b></header><OperationsMap mode="risk" :risk-points="data?.riskPoints ?? []" height="430px"/></article><aside v-if="data" class="phase6-panel risk-ranking"><header><div><strong>企业风险排序</strong><span>用于差异化监管，不替代事故认定</span></div></header><ol><li v-for="(x,i) in data.enterprises" :key="x.id"><span class="rank">{{i+1}}</span><div><strong>{{x.name}}</strong><small>告警 {{x.alerts}} · 事故 {{x.accidents}} · 违规 {{x.violations}}</small></div><b>{{x.riskScore}}</b></li></ol><el-empty v-if="!data.enterprises.length" description="暂无风险事件" :image-size="70"/></aside></section><section v-if="data" class="phase6-chart-grid"><article class="phase6-panel"><header><div><strong>事件趋势</strong><span>识别风险波动与集中日期</span></div></header><AnalyticsChart :option="trendOption"/></article><article class="phase6-panel"><header><div><strong>事件类型构成</strong><span>告警、事故、违规分类统计</span></div></header><AnalyticsChart :option="typeOption"/></article></section></template></template>
