<script setup lang="ts">
import { computed, onMounted, reactive, ref, watch } from 'vue';
import { ElMessage, ElMessageBox } from 'element-plus';
import { MoreHorizontal, Plus, RefreshCw, Search } from 'lucide-vue-next';
import { api } from '../api';
import PageHeader from '../components/PageHeader.vue';
import { useSessionStore } from '../stores/session';
import type { PageData } from '../types';

const session=useSessionStore(),rows=ref<any[]>([]),total=ref(0),loading=ref(false),error=ref(''),selected=ref<any[]>([]);
const q=ref(''),status=ref(''),enterpriseId=ref(''),modelId=ref(''),page=ref(1),pageSize=20,sort=ref('updatedAt');
const options=reactive<{models:any[];enterprises:any[];manufacturers:any[]}>({models:[],enterprises:[],manufacturers:[]});
const dialog=ref(false),saving=ref(false),editingId=ref('');
const licenseDialog=ref(false),licenseSaving=ref(false),licenseVehicle=ref<any>(null),licenses=ref<any[]>([]);
const canWrite=computed(()=>session.user?.permissions.includes('archive:vehicle:write'));
const canLicense=computed(()=>session.user?.permissions.includes('archive:license:write'));
const isEnterprise=computed(()=>session.user?.portal==='ENTERPRISE');
const form=reactive({businessNo:'',vin:'',deviceNo:'',name:'',modelId:'',enterpriseId:'',color:'',manufactureDate:'',serviceStartDate:''});
const licenseForm=reactive({businessNo:'',licenseNo:'',issuedAt:'',expiresAt:'',remark:''});
let timer:number|undefined;

async function loadOptions(){const data=await api<any>('/archives/options');Object.assign(options,data)}
async function load(){loading.value=true;error.value='';try{const p=new URLSearchParams({page:String(page.value),pageSize:String(pageSize),sort:sort.value,order:'desc'});if(q.value)p.set('q',q.value);if(status.value)p.set('status',status.value);if(enterpriseId.value)p.set('enterpriseId',enterpriseId.value);if(modelId.value)p.set('modelId',modelId.value);const data=await api<PageData<any>>(`/archives/vehicles?${p}`);rows.value=data.items;total.value=data.total}catch(reason){error.value=reason instanceof Error?reason.message:'车辆列表加载失败'}finally{loading.value=false}}
watch([q,status,enterpriseId,modelId,sort],()=>{page.value=1;clearTimeout(timer);timer=window.setTimeout(load,180)});watch(page,load);onMounted(()=>Promise.all([load(),loadOptions()]));
function toDate(value?:string){return value?value.slice(0,10):''}
function openForm(row?:any){editingId.value=row?.id??'';Object.assign(form,row?{businessNo:row.businessNo,vin:row.vin,deviceNo:row.deviceNo,name:row.name,modelId:row.modelId,enterpriseId:row.enterpriseId,color:row.color??'',manufactureDate:toDate(row.manufactureDate),serviceStartDate:toDate(row.serviceStartDate)}:{businessNo:'',vin:'',deviceNo:'',name:'',modelId:'',enterpriseId:isEnterprise.value?session.user?.enterpriseId??'':'',color:'',manufactureDate:'',serviceStartDate:''});dialog.value=true}
async function save(){if(!form.businessNo||!form.vin||!form.deviceNo||!form.name||!form.modelId||(!isEnterprise.value&&!form.enterpriseId))return ElMessage.warning('请完整填写车辆编号、VIN、设备号、名称、车型和所属企业');saving.value=true;try{await api(editingId.value?`/archives/vehicles/${editingId.value}`:'/archives/vehicles',{method:editingId.value?'PATCH':'POST',body:JSON.stringify(form)});ElMessage.success(editingId.value?'车辆信息已保存':'车辆已建档');dialog.value=false;await load()}catch(reason){ElMessage.error(reason instanceof Error?reason.message:'保存失败')}finally{saving.value=false}}
async function setStatus(targets:any[],value:string){try{await Promise.all(targets.map(row=>api(`/archives/vehicles/${row.id}/status`,{method:'PATCH',body:JSON.stringify({status:value})})));ElMessage.success(`已更新 ${targets.length} 辆车状态`);selected.value=[];await load()}catch(reason){ElMessage.error(reason instanceof Error?reason.message:'状态更新失败')}}
async function remove(targets:any[]){await ElMessageBox.confirm(`确定将选中的 ${targets.length} 辆车退出运营？车辆会保留历史档案，牌照同步注销。`,'车辆退出运营',{type:'warning',confirmButtonText:'确认退出'});try{for(const row of targets)await api(`/archives/vehicles/${row.id}`,{method:'DELETE'});ElMessage.success('车辆已退出运营并转入历史档案');selected.value=[];await load()}catch(reason){ElMessage.error(reason instanceof Error?reason.message:'操作失败')}}
async function openLicenses(row:any){licenseVehicle.value=row;licenseDialog.value=true;licenses.value=await api<any[]>(`/archives/vehicles/${row.id}/licenses`);Object.assign(licenseForm,{businessNo:'',licenseNo:'',issuedAt:'',expiresAt:'',remark:''})}
async function addLicense(){if(!licenseForm.businessNo||!licenseForm.licenseNo||!licenseForm.issuedAt||!licenseForm.expiresAt)return ElMessage.warning('请完整填写牌照编号、号牌和有效期');licenseSaving.value=true;try{await api('/archives/licenses',{method:'POST',body:JSON.stringify({...licenseForm,vehicleId:licenseVehicle.value.id})});ElMessage.success('牌照已签发');licenses.value=await api<any[]>(`/archives/vehicles/${licenseVehicle.value.id}/licenses`);await load();Object.assign(licenseForm,{businessNo:'',licenseNo:'',issuedAt:'',expiresAt:'',remark:''})}catch(reason){ElMessage.error(reason instanceof Error?reason.message:'牌照保存失败')}finally{licenseSaving.value=false}}
async function changeLicense(row:any,value:string){try{await api(`/archives/licenses/${row.id}`,{method:'PATCH',body:JSON.stringify({status:value})});ElMessage.success('牌照状态已更新');licenses.value=await api<any[]>(`/archives/vehicles/${licenseVehicle.value.id}/licenses`);await load()}catch(reason){ElMessage.error(reason instanceof Error?reason.message:'更新失败')}}
function command(row:any,action:string){if(action==='edit')openForm(row);if(action==='license')openLicenses(row);if(action==='enable')setStatus([row],'ACTIVE');if(action==='disable')setStatus([row],'INACTIVE');if(action==='delete')remove([row])}
</script>
<template>
  <PageHeader :title="isEnterprise?'我的车辆':'车辆管理'" :description="isEnterprise?'维护本企业车辆主体信息、运营状态与牌照。':'维护车辆业务信息；监管档案在独立只读页面查看。'" :count="total"><el-button :icon="RefreshCw" @click="load">刷新</el-button><el-button v-if="canWrite" type="primary" :icon="Plus" @click="openForm()">新增车辆</el-button></PageHeader>
  <div class="table-toolbar"><el-input v-model="q" :prefix-icon="Search" clearable placeholder="搜索车辆、VIN、设备号或牌照" aria-label="搜索车辆"/><el-select v-if="!isEnterprise" v-model="enterpriseId" clearable filterable placeholder="全部企业" aria-label="所属企业"><el-option v-for="item in options.enterprises" :key="item.id" :label="item.name" :value="item.id"/></el-select><el-select v-model="modelId" clearable filterable placeholder="全部车型" aria-label="车辆车型"><el-option v-for="item in options.models" :key="item.id" :label="`${item.name} · ${item.modelCode}`" :value="item.id"/></el-select><el-select v-model="status" clearable placeholder="全部状态" aria-label="车辆状态"><el-option label="运营中" value="ACTIVE"/><el-option label="已停用" value="INACTIVE"/></el-select><el-button v-if="q||status||enterpriseId||modelId" text @click="q='';status='';enterpriseId='';modelId=''">清除筛选</el-button></div>
  <div v-if="selected.length&&canWrite" class="bulk-bar"><strong>已选 {{selected.length}} 辆</strong><el-button size="small" @click="setStatus(selected,'ACTIVE')">启用</el-button><el-button size="small" @click="setStatus(selected,'INACTIVE')">停用</el-button><el-button size="small" type="danger" plain @click="remove(selected)">退出运营</el-button><el-button size="small" text @click="selected=[]">取消选择</el-button></div>
  <div v-if="error" class="error-state"><strong>车辆列表暂时无法加载</strong><span>{{error}}</span><el-button @click="load">重试</el-button></div>
  <el-table v-else v-loading="loading" :data="rows" row-key="id" empty-text="暂无符合条件的车辆" @selection-change="selected=$event">
    <el-table-column v-if="canWrite" type="selection" width="46"/><el-table-column label="车辆" min-width="220"><template #default="{row}"><div class="identity-cell"><strong>{{row.name}}</strong><span>{{row.businessNo}} · {{row.deviceNo}}</span></div></template></el-table-column><el-table-column label="VIN" prop="vin" min-width="180"/><el-table-column v-if="!isEnterprise" label="所属企业" min-width="190"><template #default="{row}">{{row.enterprise.name}}</template></el-table-column><el-table-column label="车型" min-width="170"><template #default="{row}"><div class="identity-cell"><strong>{{row.model.name}}</strong><span>{{row.model.manufacturer.shortName||row.model.manufacturer.name}}</span></div></template></el-table-column><el-table-column label="当前牌照" min-width="135"><template #default="{row}">{{row.licenses[0]?.licenseNo||'未签发'}}</template></el-table-column><el-table-column label="连接" width="86"><template #default="{row}"><span class="status-mark" :class="row.onlineStatus==='ONLINE'?'active':'inactive'"><i></i>{{row.onlineStatus==='ONLINE'?'在线':'离线'}}</span></template></el-table-column><el-table-column label="状态" width="90"><template #default="{row}"><span class="status-mark" :class="row.status.toLowerCase()"><i></i>{{row.status==='ACTIVE'?'运营中':'已停用'}}</span></template></el-table-column>
    <el-table-column label="" width="58" align="right"><template #default="{row}"><el-dropdown trigger="click" @command="(value:string)=>command(row,value)"><el-button text circle aria-label="更多车辆操作"><MoreHorizontal :size="17"/></el-button><template #dropdown><el-dropdown-menu><el-dropdown-item v-if="canWrite" command="edit">编辑车辆</el-dropdown-item><el-dropdown-item command="license">牌照管理</el-dropdown-item><el-dropdown-item v-if="canWrite" :command="row.status==='ACTIVE'?'disable':'enable'">{{row.status==='ACTIVE'?'停用':'启用'}}</el-dropdown-item><el-dropdown-item v-if="canWrite" command="delete" divided>退出运营</el-dropdown-item></el-dropdown-menu></template></el-dropdown></template></el-table-column>
  </el-table><div class="pagination-row"><span>当前显示 {{rows.length}} / {{total}}</span><el-pagination v-model:current-page="page" :page-size="pageSize" :total="total" layout="prev, pager, next"/></div>
  <el-dialog v-model="dialog" :title="editingId?'编辑车辆':'新增车辆并建档'" width="700px" destroy-on-close><p class="dialog-note">新增车辆会同步生成唯一监管档案，企业归属由登录数据范围约束。</p><div class="form-grid"><el-form-item label="车辆编号" required><el-input v-model="form.businessNo" placeholder="VEH-2026-031"/></el-form-item><el-form-item label="车辆名称" required><el-input v-model="form.name"/></el-form-item><el-form-item label="VIN" required><el-input v-model="form.vin"/></el-form-item><el-form-item label="设备编号" required><el-input v-model="form.deviceNo"/></el-form-item><el-form-item label="车型" required><el-select v-model="form.modelId" filterable><el-option v-for="item in options.models" :key="item.id" :label="`${item.name} · ${item.modelCode}`" :value="item.id"/></el-select></el-form-item><el-form-item v-if="!isEnterprise" label="所属企业" required><el-select v-model="form.enterpriseId" filterable><el-option v-for="item in options.enterprises" :key="item.id" :label="item.name" :value="item.id"/></el-select></el-form-item><el-form-item label="车身颜色"><el-input v-model="form.color"/></el-form-item><el-form-item label="生产日期"><el-date-picker v-model="form.manufactureDate" value-format="YYYY-MM-DD" type="date"/></el-form-item><el-form-item label="投运日期"><el-date-picker v-model="form.serviceStartDate" value-format="YYYY-MM-DD" type="date"/></el-form-item></div><template #footer><el-button @click="dialog=false">取消</el-button><el-button type="primary" :loading="saving" @click="save">保存车辆</el-button></template></el-dialog>
  <el-dialog v-model="licenseDialog" :title="`牌照管理 · ${licenseVehicle?.name||''}`" width="760px"><el-table :data="licenses" empty-text="该车辆尚未签发牌照"><el-table-column label="牌照号"><template #default="{row}"><div class="identity-cell"><strong>{{row.licenseNo}}</strong><span>{{row.businessNo}}</span></div></template></el-table-column><el-table-column label="有效期"><template #default="{row}">{{toDate(row.issuedAt)}} 至 {{toDate(row.expiresAt)}}</template></el-table-column><el-table-column label="状态" width="100"><template #default="{row}"><el-tag size="small" :type="row.status==='VALID'?'success':'info'">{{({VALID:'有效',EXPIRED:'过期',SUSPENDED:'暂停',CANCELLED:'注销'} as any)[row.status]}}</el-tag></template></el-table-column><el-table-column v-if="canLicense" label="" width="120"><template #default="{row}"><el-dropdown @command="(value:string)=>changeLicense(row,value)"><el-button text>变更状态</el-button><template #dropdown><el-dropdown-menu><el-dropdown-item command="VALID">恢复有效</el-dropdown-item><el-dropdown-item command="SUSPENDED">暂停</el-dropdown-item><el-dropdown-item command="CANCELLED">注销</el-dropdown-item></el-dropdown-menu></template></el-dropdown></template></el-table-column></el-table><template v-if="canLicense"><div class="subsection-title"><strong>签发新牌照</strong><span>新牌照会保留既有牌照历史</span></div><div class="form-grid"><el-form-item label="业务编号" required><el-input v-model="licenseForm.businessNo" placeholder="LIC-BIZ-031"/></el-form-item><el-form-item label="牌照号" required><el-input v-model="licenseForm.licenseNo" placeholder="浙杭无配031"/></el-form-item><el-form-item label="签发日期" required><el-date-picker v-model="licenseForm.issuedAt" value-format="YYYY-MM-DD" type="date"/></el-form-item><el-form-item label="有效期至" required><el-date-picker v-model="licenseForm.expiresAt" value-format="YYYY-MM-DD" type="date"/></el-form-item><el-form-item label="备注" class="form-span-2"><el-input v-model="licenseForm.remark"/></el-form-item></div></template><template #footer><el-button @click="licenseDialog=false">关闭</el-button><el-button v-if="canLicense" type="primary" :loading="licenseSaving" @click="addLicense">签发牌照</el-button></template></el-dialog>
</template>
