<script setup lang="ts">
import { computed, onMounted, reactive, ref, watch } from 'vue';
import { useRoute } from 'vue-router';
import { CirclePause, CirclePlay, RefreshCcw, Search } from 'lucide-vue-next';
import { ElMessage } from 'element-plus';
import { api } from '../api';import OperationsMap from '../components/OperationsMap.vue';import PageHeader from '../components/PageHeader.vue';import { useSessionStore } from '../stores/session';import type { PageData, TrackPoint } from '../types';
const route=useRoute(),session=useSessionStore(),mapRef=ref<any>(),loading=ref(false),error=ref(''),vehicleId=ref(String(route.query.vehicleId??'')),recordId=ref(''),dateRange=ref<[string,string]|null>(null),points=ref<TrackPoint[]>([]),records=ref<any[]>([]),playing=ref(false),paused=ref(false);const options=reactive<any>({vehicles:[]});const isEnterprise=computed(()=>session.user?.portal==='ENTERPRISE');
const events=computed(()=>points.value.filter(p=>p.pointType!=='NORMAL'));const maxSpeed=computed(()=>Math.max(0,...points.value.map(p=>p.speed)));const avgSpeed=computed(()=>points.value.length?Math.round(points.value.reduce((s,p)=>s+p.speed,0)/points.value.length*10)/10:0);const distanceLabel=computed(()=>records.value.find(r=>r.id===recordId.value)?.mileage??'--');
async function loadOptions(){Object.assign(options,await api<any>('/operations/options'));if(!vehicleId.value)vehicleId.value=options.vehicles[0]?.id??''}
async function loadRecords(){if(!vehicleId.value){records.value=[];return}const p=new URLSearchParams({vehicleId:vehicleId.value,page:'1',pageSize:'100'});const result=await api<PageData<any>>(`/operations/records?${p}`);records.value=result.items;if(!records.value.some(r=>r.id===recordId.value))recordId.value=records.value[0]?.id??''}
async function queryTrack(){if(!vehicleId.value)return ElMessage.warning('请先选择车辆');loading.value=true;error.value='';try{const p=new URLSearchParams();if(recordId.value)p.set('recordId',recordId.value);else if(dateRange.value){p.set('from',dateRange.value[0]);p.set('to',dateRange.value[1])}const data=await api<any>(`/operations/vehicles/${vehicleId.value}/tracks?${p}`);points.value=data.points;playing.value=false;paused.value=false;if(!points.value.length)ElMessage.info('所选范围暂无轨迹点')}catch(reason){error.value=reason instanceof Error?reason.message:'轨迹加载失败'}finally{loading.value=false}}
watch(vehicleId,async()=>{recordId.value='';await loadRecords();await queryTrack()});watch(recordId,()=>queryTrack());onMounted(async()=>{await loadOptions();await loadRecords();await queryTrack()});
function play(){mapRef.value?.playTrack();playing.value=true;paused.value=false}function pause(){mapRef.value?.pauseTrack();paused.value=true}function resume(){mapRef.value?.resumeTrack();paused.value=false}function stop(){mapRef.value?.stopTrack();playing.value=false;paused.value=false}const fmt=(v:string)=>new Date(v).toLocaleString('zh-CN',{month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit'});
</script>
<template><PageHeader title="车辆轨迹" :description="isEnterprise?'查询本企业车辆轨迹与驾驶状态变化。':'统一的轨迹取证能力，可供运行记录、事故回溯与告警核查复用。'" :count="points.length"/>
  <div class="trajectory-query"><el-select v-model="vehicleId" filterable placeholder="选择车辆" aria-label="轨迹车辆"><el-option v-for="item in options.vehicles" :key="item.id" :label="`${item.name} · ${item.businessNo}`" :value="item.id"/></el-select><el-select v-model="recordId" clearable filterable placeholder="按运行记录（可清空）" aria-label="运行记录"><el-option v-for="item in records" :key="item.id" :label="`${item.businessNo} · ${fmt(item.startedAt)}`" :value="item.id"/></el-select><el-date-picker v-model="dateRange" type="datetimerange" value-format="YYYY-MM-DDTHH:mm:ssZ" start-placeholder="开始时间" end-placeholder="结束时间" :disabled="!!recordId"/><el-button type="primary" :icon="Search" :loading="loading" @click="queryTrack">查询轨迹</el-button></div>
  <div v-if="error" class="error-state"><strong>轨迹暂时无法加载</strong><span>{{error}}</span><el-button @click="queryTrack">重试</el-button></div><template v-else><div class="trajectory-stats"><div><span>轨迹点</span><strong>{{points.length}}</strong></div><div><span>运行里程</span><strong>{{distanceLabel}} km</strong></div><div><span>平均速度</span><strong>{{avgSpeed}} km/h</strong></div><div><span>最高速度</span><strong>{{maxSpeed}} km/h</strong></div><div><span>停留 / 事件</span><strong>{{events.filter(e=>e.pointType==='STOP').length}} / {{events.filter(e=>e.pointType==='ALERT').length}}</strong></div></div><div class="trajectory-layout"><div><OperationsMap ref="mapRef" mode="trajectory" :track="points" height="570px"/><div class="replay-bar"><div><el-button v-if="!playing" type="primary" :icon="CirclePlay" :disabled="points.length<2" @click="play">开始回放</el-button><el-button v-else-if="!paused" :icon="CirclePause" @click="pause">暂停</el-button><el-button v-else type="primary" :icon="CirclePlay" @click="resume">继续</el-button><el-button :icon="RefreshCcw" :disabled="!playing" @click="stop">复位</el-button></div><span>按轨迹时间顺序回放 · 地图自动旋转车辆方向</span></div></div><aside class="trajectory-analysis"><section><header><strong>速度变化</strong><span>{{avgSpeed}} km/h 均速</span></header><div class="speed-bars" aria-label="轨迹速度变化图"><i v-for="point in points" :key="point.id" :style="{height:`${Math.max(3,point.speed/Math.max(maxSpeed,1)*100)}%`}" :class="{stop:point.speed===0,alert:point.pointType==='ALERT'}" :title="`${fmt(point.recordedAt)} · ${point.speed} km/h`"></i></div></section><section><header><strong>关键节点</strong><span>{{events.length}} 个</span></header><div class="event-list"><div v-for="point in events" :key="point.id"><i :class="point.pointType.toLowerCase()"></i><span><strong>{{point.pointType==='STOP'?'车辆停留':'驾驶状态事件'}}</strong><small>{{fmt(point.recordedAt)}} · {{point.speed}} km/h · 电量 {{point.battery}}%</small></span></div><p v-if="!events.length">所选轨迹无关键事件</p></div></section></aside></div></template>
</template>
