<script setup lang="ts">
import { computed, onMounted, ref, watch } from 'vue';
import { ElMessage } from 'element-plus';
import { FileSearch, RefreshCw, Search } from 'lucide-vue-next';
import { api } from '../api';
import PageHeader from '../components/PageHeader.vue';
import { useSessionStore } from '../stores/session';
import type { PageData } from '../types';

const session=useSessionStore(),rows=ref<any[]>([]),total=ref(0),loading=ref(false),error=ref(''),q=ref(''),status=ref(''),enterpriseId=ref(''),page=ref(1),pageSize=20;
const enterprises=ref<any[]>([]),drawer=ref(false),detailLoading=ref(false),detail=ref<any>(null),activeTab=ref('basic');
const isEnterprise=computed(()=>session.user?.portal==='ENTERPRISE');let timer:number|undefined;
const date=(value?:string)=>value?new Date(value).toLocaleDateString('zh-CN'):'—';
async function loadOptions(){if(!isEnterprise.value){const data=await api<any>('/archives/options');enterprises.value=data.enterprises}}
async function load(){loading.value=true;error.value='';try{const p=new URLSearchParams({page:String(page.value),pageSize:String(pageSize),sort:'updatedAt',order:'desc'});if(q.value)p.set('q',q.value);if(status.value)p.set('status',status.value);if(enterpriseId.value)p.set('enterpriseId',enterpriseId.value);const data=await api<PageData<any>>(`/archives/vehicles?${p}`);rows.value=data.items;total.value=data.total}catch(reason){error.value=reason instanceof Error?reason.message:'车辆档案加载失败'}finally{loading.value=false}}
watch([q,status,enterpriseId],()=>{page.value=1;clearTimeout(timer);timer=window.setTimeout(load,180)});watch(page,load);onMounted(()=>Promise.all([load(),loadOptions()]));
async function open(row:any){drawer.value=true;detailLoading.value=true;detail.value=null;activeTab.value='basic';try{detail.value=await api<any>(`/archives/vehicles/${row.id}`)}catch(reason){ElMessage.error(reason instanceof Error?reason.message:'档案加载失败');drawer.value=false}finally{detailLoading.value=false}}
</script>
<template>
  <PageHeader title="车辆档案" :description="isEnterprise?'查看本企业车辆从建档、投运到退出的完整监管记录。':'只读查看车辆身份、运营状态、牌照和生命周期记录。'" :count="total"><el-button :icon="RefreshCw" @click="load">刷新</el-button></PageHeader>
  <div class="table-toolbar"><el-input v-model="q" :prefix-icon="Search" clearable placeholder="搜索车辆、档案号、VIN 或牌照" aria-label="搜索车辆档案"/><el-select v-if="!isEnterprise" v-model="enterpriseId" clearable filterable placeholder="全部企业" aria-label="所属企业"><el-option v-for="item in enterprises" :key="item.id" :label="item.name" :value="item.id"/></el-select><el-select v-model="status" clearable placeholder="全部状态" aria-label="档案状态"><el-option label="运营中" value="ACTIVE"/><el-option label="暂停" value="INACTIVE"/></el-select><el-button v-if="q||status||enterpriseId" text @click="q='';status='';enterpriseId=''">清除筛选</el-button></div>
  <div v-if="error" class="error-state"><strong>车辆档案暂时无法加载</strong><span>{{error}}</span><el-button @click="load">重试</el-button></div>
  <el-table v-else v-loading="loading" :data="rows" empty-text="暂无符合条件的车辆档案" @row-click="open">
    <el-table-column label="档案标识" min-width="210"><template #default="{row}"><button class="table-link" @click.stop="open(row)"><strong>{{row.archive?.archiveNo}}</strong><span>{{row.businessNo}}</span></button></template></el-table-column><el-table-column label="车辆" min-width="190"><template #default="{row}"><div class="identity-cell"><strong>{{row.name}}</strong><span>{{row.vin}}</span></div></template></el-table-column><el-table-column v-if="!isEnterprise" label="所属企业" min-width="190"><template #default="{row}">{{row.enterprise.name}}</template></el-table-column><el-table-column label="厂商 / 车型" min-width="220"><template #default="{row}"><div class="identity-cell"><strong>{{row.model.manufacturer.shortName||row.model.manufacturer.name}}</strong><span>{{row.model.name}} · {{row.model.modelCode}}</span></div></template></el-table-column><el-table-column label="牌照" min-width="130"><template #default="{row}">{{row.licenses[0]?.licenseNo||'未签发'}}</template></el-table-column><el-table-column label="生命周期" width="110"><template #default="{row}"><el-tag size="small" effect="plain" :type="row.archive?.lifecycleStatus==='IN_SERVICE'?'success':'info'">{{row.archive?.lifecycleStatus==='IN_SERVICE'?'在运':'暂停'}}</el-tag></template></el-table-column><el-table-column label="" width="42"><template #default><FileSearch :size="16" class="row-affordance"/></template></el-table-column>
  </el-table><div class="pagination-row"><span>当前显示 {{rows.length}} / {{total}}</span><el-pagination v-model:current-page="page" :page-size="pageSize" :total="total" layout="prev, pager, next"/></div>
  <el-drawer v-model="drawer" size="720px" destroy-on-close><template #header><div v-if="detail" class="archive-drawer-title"><div><span>{{detail.archive?.archiveNo}}</span><h2>{{detail.name}}</h2></div><span class="status-mark" :class="detail.status.toLowerCase()"><i></i>{{detail.status==='ACTIVE'?'运营中':'已停用'}}</span></div></template><div v-loading="detailLoading"><template v-if="detail"><div class="archive-identity"><div><span>VIN</span><strong>{{detail.vin}}</strong></div><div><span>设备编号</span><strong>{{detail.deviceNo}}</strong></div><div><span>所属企业</span><strong>{{detail.enterprise.name}}</strong></div></div><el-tabs v-model="activeTab">
    <el-tab-pane label="基本信息" name="basic"><dl class="detail-grid"><div><dt>车辆编号</dt><dd>{{detail.businessNo}}</dd></div><div><dt>档案编号</dt><dd>{{detail.archive?.archiveNo}}</dd></div><div><dt>生产厂商</dt><dd>{{detail.model.manufacturer.name}}</dd></div><div><dt>车型</dt><dd>{{detail.model.name}}（{{detail.model.modelCode}}）</dd></div><div><dt>车身颜色</dt><dd>{{detail.color||'—'}}</dd></div><div><dt>生产日期</dt><dd>{{date(detail.manufactureDate)}}</dd></div><div><dt>监管机构</dt><dd>{{detail.organization.name}}</dd></div><div><dt>建档日期</dt><dd>{{date(detail.archive?.registeredAt)}}</dd></div></dl></el-tab-pane>
    <el-tab-pane label="运行信息" name="operation"><div class="metric-strip archive-metrics"><div><span>连接状态</span><strong>{{detail.onlineStatus==='ONLINE'?'在线':'离线'}}</strong></div><div><span>最高车速</span><strong>{{detail.model.maxSpeed}} km/h</strong></div><div><span>额定续航</span><strong>{{detail.model.ratedRange}} km</strong></div><div><span>额定载重</span><strong>{{detail.model.loadCapacity}} kg</strong></div></div><dl class="detail-grid"><div><dt>投运日期</dt><dd>{{date(detail.serviceStartDate)}}</dd></div><div><dt>自动驾驶等级</dt><dd>{{detail.model.autonomyLevel}}</dd></div><div><dt>车辆类型</dt><dd>{{detail.model.vehicleType==='DELIVERY'?'无人配送车':detail.model.vehicleType}}</dd></div><div><dt>外形尺寸</dt><dd>{{detail.model.dimensions||'—'}}</dd></div></dl></el-tab-pane>
    <el-tab-pane :label="`牌照信息 ${detail.licenses.length}`" name="licenses"><el-table :data="detail.licenses" empty-text="该车辆尚未签发牌照"><el-table-column label="牌照号"><template #default="{row}"><div class="identity-cell"><strong>{{row.licenseNo}}</strong><span>{{row.businessNo}}</span></div></template></el-table-column><el-table-column label="签发日期"><template #default="{row}">{{date(row.issuedAt)}}</template></el-table-column><el-table-column label="有效期至"><template #default="{row}">{{date(row.expiresAt)}}</template></el-table-column><el-table-column label="状态"><template #default="{row}">{{({VALID:'有效',EXPIRED:'过期',SUSPENDED:'暂停',CANCELLED:'注销'} as any)[row.status]}}</template></el-table-column></el-table></el-tab-pane>
    <el-tab-pane label="历史记录" name="history"><el-timeline><el-timeline-item :timestamp="date(detail.archive?.registeredAt)" type="primary">车辆完成监管建档并进入生命周期管理</el-timeline-item><el-timeline-item v-if="detail.serviceStartDate" :timestamp="date(detail.serviceStartDate)" type="success">车辆投入运营</el-timeline-item><el-timeline-item v-for="item in detail.licenses" :key="item.id" :timestamp="date(item.issuedAt)">签发牌照 {{item.licenseNo}}</el-timeline-item><el-timeline-item v-if="detail.archive?.exitedAt" :timestamp="date(detail.archive.exitedAt)" type="danger">车辆退出运营</el-timeline-item></el-timeline></el-tab-pane>
  </el-tabs></template></div></el-drawer>
</template>
