<script setup lang="ts">
import { computed, onMounted, reactive, ref, watch } from 'vue';
import { ElMessage, ElMessageBox } from 'element-plus';
import { MoreHorizontal, Plus, RefreshCw, Search } from 'lucide-vue-next';
import { api } from '../api';
import PageHeader from '../components/PageHeader.vue';
import { useSessionStore } from '../stores/session';
import type { PageData } from '../types';

const session = useSessionStore(), rows = ref<any[]>([]), manufacturers = ref<any[]>([]), total = ref(0), loading = ref(false), error = ref('');
const q = ref(''), status = ref(''), manufacturerId = ref(''), sort = ref('updatedAt'), selected = ref<any[]>([]), page = ref(1), pageSize = 20;
const dialog = ref(false), saving = ref(false), editingId = ref('');
const canWrite = computed(() => session.user?.permissions.includes('archive:model:write'));
const form = reactive({ businessNo:'', modelCode:'', name:'', manufacturerId:'', vehicleType:'DELIVERY', autonomyLevel:'L4', maxSpeed:25, ratedRange:120, loadCapacity:1000, dimensions:'' });
let timer:number|undefined;
async function loadOptions(){const data=await api<PageData<any>>('/archives/manufacturers?page=1&pageSize=100&status=ACTIVE&sort=name&order=asc');manufacturers.value=data.items}
async function load(){loading.value=true;error.value='';try{const p=new URLSearchParams({page:String(page.value),pageSize:String(pageSize),sort:sort.value,order:sort.value==='name'?'asc':'desc'});if(q.value)p.set('q',q.value);if(status.value)p.set('status',status.value);if(manufacturerId.value)p.set('manufacturerId',manufacturerId.value);const data=await api<PageData<any>>(`/archives/models?${p}`);rows.value=data.items;total.value=data.total}catch(reason){error.value=reason instanceof Error?reason.message:'车型列表加载失败'}finally{loading.value=false}}
watch([q,status,manufacturerId,sort],()=>{page.value=1;clearTimeout(timer);timer=window.setTimeout(load,180)});watch(page,load);onMounted(()=>Promise.all([load(),loadOptions()]));
function openForm(row?:any){editingId.value=row?.id??'';Object.assign(form,row?{businessNo:row.businessNo,modelCode:row.modelCode,name:row.name,manufacturerId:row.manufacturerId,vehicleType:row.vehicleType,autonomyLevel:row.autonomyLevel,maxSpeed:row.maxSpeed,ratedRange:row.ratedRange,loadCapacity:row.loadCapacity,dimensions:row.dimensions??''}:{businessNo:'',modelCode:'',name:'',manufacturerId:'',vehicleType:'DELIVERY',autonomyLevel:'L4',maxSpeed:25,ratedRange:120,loadCapacity:1000,dimensions:''});dialog.value=true}
async function save(){if(!form.businessNo||!form.modelCode||!form.name||!form.manufacturerId)return ElMessage.warning('请填写编号、型号代码、名称和厂商');saving.value=true;try{await api(editingId.value?`/archives/models/${editingId.value}`:'/archives/models',{method:editingId.value?'PATCH':'POST',body:JSON.stringify(form)});ElMessage.success(editingId.value?'车型已更新':'车型已新增');dialog.value=false;await load()}catch(reason){ElMessage.error(reason instanceof Error?reason.message:'保存失败')}finally{saving.value=false}}
async function setStatus(targets:any[],value:string){try{await Promise.all(targets.map(row=>api(`/archives/models/${row.id}/status`,{method:'PATCH',body:JSON.stringify({status:value})})));ElMessage.success(`已更新 ${targets.length} 个车型状态`);selected.value=[];await load()}catch(reason){ElMessage.error(reason instanceof Error?reason.message:'状态更新失败')}}
async function remove(targets:any[]){await ElMessageBox.confirm(`确定删除选中的 ${targets.length} 个车型？有关联车辆的车型不会被删除。`,'删除车型',{type:'warning',confirmButtonText:'删除'});try{for(const row of targets)await api(`/archives/models/${row.id}`,{method:'DELETE'});ElMessage.success('车型已删除');selected.value=[];await load()}catch(reason){ElMessage.error(reason instanceof Error?reason.message:'删除失败')}}
function command(row:any,action:string){if(action==='edit')openForm(row);if(action==='enable')setStatus([row],'ACTIVE');if(action==='disable')setStatus([row],'INACTIVE');if(action==='delete')remove([row])}
</script>
<template>
  <PageHeader title="车型管理" description="维护车型技术参数及其生产厂商关系。" :count="total"><el-button :icon="RefreshCw" @click="load">刷新</el-button><el-button v-if="canWrite" type="primary" :icon="Plus" @click="openForm()">新增车型</el-button></PageHeader>
  <div class="table-toolbar"><el-input v-model="q" :prefix-icon="Search" clearable placeholder="搜索车型名称、代码或编号" aria-label="搜索车型"/><el-select v-model="manufacturerId" clearable placeholder="全部厂商" aria-label="生产厂商"><el-option v-for="item in manufacturers" :key="item.id" :label="item.shortName||item.name" :value="item.id"/></el-select><el-select v-model="status" clearable placeholder="全部状态" aria-label="车型状态"><el-option label="正常" value="ACTIVE"/><el-option label="停用" value="INACTIVE"/></el-select><el-select v-model="sort" aria-label="排序方式"><el-option label="最近更新" value="updatedAt"/><el-option label="名称排序" value="name"/></el-select><el-button v-if="q||status||manufacturerId" text @click="q='';status='';manufacturerId=''">清除筛选</el-button></div>
  <div v-if="selected.length&&canWrite" class="bulk-bar"><strong>已选 {{selected.length}} 项</strong><el-button size="small" @click="setStatus(selected,'ACTIVE')">启用</el-button><el-button size="small" @click="setStatus(selected,'INACTIVE')">停用</el-button><el-button size="small" type="danger" plain @click="remove(selected)">删除</el-button><el-button size="small" text @click="selected=[]">取消选择</el-button></div>
  <div v-if="error" class="error-state"><strong>车型列表暂时无法加载</strong><span>{{error}}</span><el-button @click="load">重试</el-button></div>
  <el-table v-else v-loading="loading" :data="rows" row-key="id" empty-text="暂无符合条件的车型" @selection-change="selected=$event">
    <el-table-column v-if="canWrite" type="selection" width="46"/><el-table-column label="车型" min-width="230"><template #default="{row}"><div class="identity-cell"><strong>{{row.name}}</strong><span>{{row.modelCode}} · {{row.businessNo}}</span></div></template></el-table-column><el-table-column label="生产厂商" min-width="190"><template #default="{row}">{{row.manufacturer.shortName||row.manufacturer.name}}</template></el-table-column><el-table-column label="自动驾驶" width="100" prop="autonomyLevel"/><el-table-column label="最高车速" width="105"><template #default="{row}">{{row.maxSpeed}} km/h</template></el-table-column><el-table-column label="续航" width="90"><template #default="{row}">{{row.ratedRange}} km</template></el-table-column><el-table-column label="载重" width="100"><template #default="{row}">{{row.loadCapacity}} kg</template></el-table-column><el-table-column label="车辆数" width="80"><template #default="{row}">{{row._count.vehicles}}</template></el-table-column><el-table-column label="状态" width="90"><template #default="{row}"><span class="status-mark" :class="row.status.toLowerCase()"><i></i>{{row.status==='ACTIVE'?'正常':'停用'}}</span></template></el-table-column>
    <el-table-column v-if="canWrite" label="" width="58" align="right"><template #default="{row}"><el-dropdown trigger="click" @command="(value:string)=>command(row,value)"><el-button text circle aria-label="更多车型操作"><MoreHorizontal :size="17"/></el-button><template #dropdown><el-dropdown-menu><el-dropdown-item command="edit">编辑</el-dropdown-item><el-dropdown-item :command="row.status==='ACTIVE'?'disable':'enable'">{{row.status==='ACTIVE'?'停用':'启用'}}</el-dropdown-item><el-dropdown-item command="delete" divided>删除</el-dropdown-item></el-dropdown-menu></template></el-dropdown></template></el-table-column>
  </el-table><div class="pagination-row"><span>当前显示 {{rows.length}} / {{total}}</span><el-pagination v-model:current-page="page" :page-size="pageSize" :total="total" layout="prev, pager, next"/></div>
  <el-dialog v-model="dialog" :title="editingId?'编辑车型':'新增车型'" width="680px" destroy-on-close><p class="dialog-note">技术参数用于准入校验和运行监管，请按厂商定型数据填写。</p><div class="form-grid"><el-form-item label="档案编号" required><el-input v-model="form.businessNo" placeholder="MOD-009"/></el-form-item><el-form-item label="型号代码" required><el-input v-model="form.modelCode" placeholder="MODEL-X1"/></el-form-item><el-form-item label="车型名称" required><el-input v-model="form.name"/></el-form-item><el-form-item label="生产厂商" required><el-select v-model="form.manufacturerId" filterable><el-option v-for="item in manufacturers" :key="item.id" :label="item.name" :value="item.id"/></el-select></el-form-item><el-form-item label="自动驾驶等级"><el-select v-model="form.autonomyLevel"><el-option label="L4" value="L4"/><el-option label="L3" value="L3"/></el-select></el-form-item><el-form-item label="车辆类型"><el-select v-model="form.vehicleType"><el-option label="无人配送车" value="DELIVERY"/><el-option label="无人零售车" value="RETAIL"/></el-select></el-form-item><el-form-item label="最高车速（km/h）"><el-input-number v-model="form.maxSpeed" :min="1" :max="120"/></el-form-item><el-form-item label="额定续航（km）"><el-input-number v-model="form.ratedRange" :min="1" :max="1000"/></el-form-item><el-form-item label="载重（kg）"><el-input-number v-model="form.loadCapacity" :min="1" :max="10000"/></el-form-item><el-form-item label="外形尺寸"><el-input v-model="form.dimensions" placeholder="长×宽×高 mm"/></el-form-item></div><template #footer><el-button @click="dialog=false">取消</el-button><el-button type="primary" :loading="saving" @click="save">保存车型</el-button></template></el-dialog>
</template>
