<script setup lang="ts">
import { onMounted, reactive, ref, watch } from 'vue';
import { Building2, Layers3, Map, RefreshCw } from 'lucide-vue-next';
import { api } from '../api';
import OperationsMap from '../components/OperationsMap.vue';
import PageHeader from '../components/PageHeader.vue';
import type { OperationPoint } from '../types';
const loading=ref(false),error=ref(''),layer=ref<'scatter'|'cluster'|'heat'>('cluster'),enterpriseId=ref(''),organizationId=ref(''),drivingState=ref('');
const data=reactive<any>({items:[],summary:{online:0,running:0},byEnterprise:[],byOrganization:[],byState:[]});const options=reactive<any>({enterprises:[],organizations:[]});
async function loadOptions(){Object.assign(options,await api<any>('/operations/options'))}async function load(){loading.value=true;error.value='';try{const p=new URLSearchParams();if(enterpriseId.value)p.set('enterpriseId',enterpriseId.value);if(organizationId.value)p.set('organizationId',organizationId.value);if(drivingState.value)p.set('drivingState',drivingState.value);Object.assign(data,await api<any>(`/operations/distribution?${p}`))}catch(reason){error.value=reason instanceof Error?reason.message:'车辆分布加载失败'}finally{loading.value=false}}watch([enterpriseId,organizationId,drivingState],load);onMounted(()=>Promise.all([load(),loadOptions()]));
const stateText=(value:string)=>({RUNNING:'运行中',IDLE:'临停',PARKED:'停驶',OFFLINE:'离线'}as any)[value]??value;
</script>
<template><PageHeader title="车辆分布" description="按空间密度、企业、行政区与运行状态研判车辆投放结构。" :count="data.items.length"><el-button :icon="RefreshCw" :loading="loading" @click="load">刷新</el-button></PageHeader>
  <div class="table-toolbar operation-toolbar"><el-select v-model="enterpriseId" clearable filterable placeholder="全部企业" aria-label="所属企业"><el-option v-for="item in options.enterprises" :key="item.id" :label="item.name" :value="item.id"/></el-select><el-select v-model="organizationId" clearable placeholder="全部行政区" aria-label="行政区"><el-option v-for="item in options.organizations" :key="item.id" :label="item.name" :value="item.id"/></el-select><el-select v-model="drivingState" clearable placeholder="全部运行状态" aria-label="运行状态"><el-option label="运行中" value="RUNNING"/><el-option label="临停" value="IDLE"/><el-option label="停驶" value="PARKED"/><el-option label="离线" value="OFFLINE"/></el-select><el-segmented v-model="layer" :options="[{label:'散点',value:'scatter'},{label:'聚合',value:'cluster'},{label:'热力',value:'heat'}]" aria-label="分布图层"/></div>
  <div v-if="error" class="error-state"><strong>分布数据暂时无法加载</strong><span>{{error}}</span><el-button @click="load">重试</el-button></div><div v-else class="distribution-grid"><OperationsMap :points="data.items as OperationPoint[]" mode="distribution" :display-layer="layer" height="610px"/><aside class="distribution-side"><section><header><Building2 :size="16"/><strong>企业分布</strong></header><div v-for="item in data.byEnterprise" :key="item.id" class="rank-row"><span>{{item.name}}</span><b>{{item.count}}</b><i :style="{width:`${Math.max(8,item.count/Math.max(...data.byEnterprise.map((x:any)=>x.count),1)*100)}%`}"></i></div></section><section><header><Map :size="16"/><strong>行政区分布</strong></header><div v-for="item in data.byOrganization" :key="item.id" class="rank-row"><span>{{item.name}}</span><b>{{item.count}}</b><i :style="{width:`${Math.max(8,item.count/Math.max(...data.byOrganization.map((x:any)=>x.count),1)*100)}%`}"></i></div></section><section><header><Layers3 :size="16"/><strong>状态构成</strong></header><div class="state-breakdown"><div v-for="item in data.byState" :key="item.id"><strong>{{item.count}}</strong><span>{{stateText(item.name)}}</span></div></div></section></aside></div>
</template>
