<script setup lang="ts">
import { computed, onMounted, reactive, ref } from 'vue';
import { ElMessage, ElMessageBox } from 'element-plus';
import { MoreHorizontal, Plus, RefreshCw, Search, Workflow } from 'lucide-vue-next';
import { api } from '../api';
import PageHeader from '../components/PageHeader.vue';
import { useSessionStore } from '../stores/session';

const session=useSessionStore(),rows=ref<any[]>([]),loading=ref(false),error=ref(''),q=ref(''),status=ref(''),dialog=ref(false),saving=ref(false);
const canWrite=computed(()=>session.user?.permissions.includes('admission:workflow:write'));
const form=reactive<any>({code:'',name:'',applicationType:'ROAD_TEST',version:1,description:'',nodes:[{nodeCode:'MATERIAL_REVIEW',name:'材料初审',orderNo:1,approvalRoleCode:'APPROVER',timeLimitHours:24,countersignMode:'ANY',canReturn:true},{nodeCode:'BUSINESS_REVIEW',name:'业务复核',orderNo:2,approvalRoleCode:'REGULATORY_ADMIN',timeLimitHours:48,countersignMode:'ANY',canReturn:true}]});
const filtered=computed(()=>rows.value.filter(row=>(!status.value||row.status===status.value)&&(!q.value||`${row.name}${row.code}${row.businessNo}`.toLowerCase().includes(q.value.toLowerCase()))));
const typeLabel=(value:string)=>({ENTERPRISE_ONBOARDING:'企业入驻',ROAD_TEST:'路测申请',LICENSE_RENEWAL:'牌照续期'} as any)[value]??value;
const statusLabel=(value:string)=>({DRAFT:'草稿',ACTIVE:'已启用',INACTIVE:'已停用'} as any)[value]??value;
async function load(){loading.value=true;error.value='';try{rows.value=await api<any[]>('/admission/workflows')}catch(reason){error.value=reason instanceof Error?reason.message:'流程定义加载失败'}finally{loading.value=false}}
onMounted(load);
function openForm(){Object.assign(form,{code:'',name:'',applicationType:'ROAD_TEST',version:1,description:'',nodes:[{nodeCode:'MATERIAL_REVIEW',name:'材料初审',orderNo:1,approvalRoleCode:'APPROVER',timeLimitHours:24,countersignMode:'ANY',canReturn:true},{nodeCode:'BUSINESS_REVIEW',name:'业务复核',orderNo:2,approvalRoleCode:'REGULATORY_ADMIN',timeLimitHours:48,countersignMode:'ANY',canReturn:true}]});dialog.value=true}
function addNode(){form.nodes.push({nodeCode:`NODE_${form.nodes.length+1}`,name:'新增审批节点',orderNo:form.nodes.length+1,approvalRoleCode:'APPROVER',timeLimitHours:48,countersignMode:'ANY',canReturn:true})}
function removeNode(index:number){form.nodes.splice(index,1);form.nodes.forEach((node:any,i:number)=>node.orderNo=i+1)}
async function save(){if(!form.code||!form.name||!form.nodes.length||form.nodes.some((node:any)=>!node.nodeCode||!node.name))return ElMessage.warning('请完整填写流程和节点信息');saving.value=true;try{await api('/admission/workflows',{method:'POST',body:JSON.stringify(form)});ElMessage.success('流程草稿已创建');dialog.value=false;await load()}catch(reason){ElMessage.error(reason instanceof Error?reason.message:'流程创建失败')}finally{saving.value=false}}
async function setStatus(row:any,value:string){try{if(value==='ACTIVE')await ElMessageBox.confirm('启用后，同申请类型的其他流程会自动停用。','启用流程',{confirmButtonText:'确认启用'});await api(`/admission/workflows/${row.id}`,{method:'PATCH',body:JSON.stringify({status:value})});ElMessage.success(value==='ACTIVE'?'流程已启用':'流程已停用');await load()}catch(reason){if(reason!=='cancel')ElMessage.error(reason instanceof Error?reason.message:'状态更新失败')}}
</script>

<template>
  <PageHeader title="流程配置" description="配置申请类型、审批节点、角色、顺序与办理时限。" :count="filtered.length"><el-button :icon="RefreshCw" @click="load">刷新</el-button><el-button v-if="canWrite" type="primary" :icon="Plus" @click="openForm">新建流程</el-button></PageHeader>
  <div class="table-toolbar"><el-input v-model="q" :prefix-icon="Search" clearable placeholder="搜索流程名称、编码或编号" aria-label="搜索流程"/><el-select v-model="status" clearable placeholder="全部状态" aria-label="流程状态"><el-option label="草稿" value="DRAFT"/><el-option label="已启用" value="ACTIVE"/><el-option label="已停用" value="INACTIVE"/></el-select></div>
  <div v-if="error" class="error-state"><strong>流程配置暂时无法加载</strong><span>{{error}}</span><el-button @click="load">重试</el-button></div>
  <el-table v-else v-loading="loading" :data="filtered" row-key="id" empty-text="暂无符合条件的流程定义"><el-table-column label="流程" min-width="260"><template #default="{row}"><div class="identity-cell"><strong>{{row.name}}</strong><span>{{row.code}} · V{{row.version}}</span></div></template></el-table-column><el-table-column label="业务类型" width="120"><template #default="{row}">{{typeLabel(row.applicationType)}}</template></el-table-column><el-table-column label="审批链" min-width="300"><template #default="{row}"><div class="node-chain"><template v-for="(node,index) in row.nodes" :key="node.id"><span><i>{{index+1}}</i>{{node.name}}<small>{{node.approvalRoleCode}} · {{node.timeLimitHours}}h</small></span><b v-if="index<row.nodes.length-1">→</b></template></div></template></el-table-column><el-table-column label="实例数" width="85"><template #default="{row}">{{row._count.instances}}</template></el-table-column><el-table-column label="状态" width="90"><template #default="{row}"><el-tag size="small" effect="plain" :type="row.status==='ACTIVE'?'success':'info'">{{statusLabel(row.status)}}</el-tag></template></el-table-column><el-table-column v-if="canWrite" label="" width="58"><template #default="{row}"><el-dropdown trigger="click"><el-button text circle aria-label="更多流程操作"><MoreHorizontal :size="17"/></el-button><template #dropdown><el-dropdown-menu><el-dropdown-item v-if="row.status!=='ACTIVE'" @click="setStatus(row,'ACTIVE')">启用流程</el-dropdown-item><el-dropdown-item v-if="row.status==='ACTIVE'" @click="setStatus(row,'INACTIVE')">停用流程</el-dropdown-item></el-dropdown-menu></template></el-dropdown></template></el-table-column></el-table>
  <el-dialog v-model="dialog" title="新建审批流程" width="820px" destroy-on-close><p class="dialog-note">流程创建后先保存为草稿，确认节点与角色无误后再从列表启用。</p><div class="form-grid"><el-form-item label="流程编码" required><el-input v-model="form.code" placeholder="ROAD_TEST_V2"/></el-form-item><el-form-item label="流程名称" required><el-input v-model="form.name"/></el-form-item><el-form-item label="申请类型" required><el-select v-model="form.applicationType"><el-option label="企业入驻" value="ENTERPRISE_ONBOARDING"/><el-option label="路测申请" value="ROAD_TEST"/><el-option label="牌照续期" value="LICENSE_RENEWAL"/></el-select></el-form-item><el-form-item label="版本"><el-input-number v-model="form.version" :min="1"/></el-form-item><el-form-item label="流程说明" class="form-span-2"><el-input v-model="form.description" type="textarea" :rows="2"/></el-form-item></div><div class="subsection-title"><strong>审批节点</strong><el-button size="small" :icon="Plus" @click="addNode">添加节点</el-button></div><div class="node-editor" v-for="(node,index) in form.nodes" :key="index"><div class="node-index"><Workflow :size="16"/><strong>{{index+1}}</strong></div><el-input v-model="node.nodeCode" placeholder="节点编码"/><el-input v-model="node.name" placeholder="节点名称"/><el-select v-model="node.approvalRoleCode"><el-option label="审批人员" value="APPROVER"/><el-option label="监管管理员" value="REGULATORY_ADMIN"/></el-select><el-input-number v-model="node.timeLimitHours" :min="1" :max="720" controls-position="right"/><el-checkbox v-model="node.canReturn">可退回</el-checkbox><el-button v-if="form.nodes.length>1" text type="danger" @click="removeNode(index)">移除</el-button></div><template #footer><el-button @click="dialog=false">取消</el-button><el-button type="primary" :loading="saving" @click="save">保存流程草稿</el-button></template></el-dialog>
</template>
